codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        threshold: 5%
    patch:
      default:
        target: 0%
