@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModtrektParser" as ModtrektParser LOGIC_COLOR
participant "cmd:ListTasksCommand" as ListTasksCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list task")
activate LogicManager

LogicManager -> ModtrektParser : parseCommand("list task")
activate ModtrektParser

create ListTasksCommand
ModtrektParser -> ListTasksCommand
activate ListTasksCommand



ListTasksCommand --> ModtrektParser
deactivate ListTasksCommand

ModtrektParser --> LogicManager : cmd
deactivate ModtrektParser
LogicManager -> ListTasksCommand : execute()
activate ListTasksCommand

alt -a flag is present

    ListTasksCommand -> Model : updateFilteredTaskList(SHOW_ALL_TASKS)
    activate Model

    Model --> ListTasksCommand
    deactivate Model

else else

    ListTasksCommand -> Model : updateFilteredTaskList(HIDE_DONE_TASKS)
    activate Model

    Model --> ListTasksCommand
    deactivate Model

end

create CommandResult
ListTasksCommand -> CommandResult
activate CommandResult

CommandResult --> ListTasksCommand
deactivate CommandResult

ListTasksCommand --> LogicManager : result
deactivate ListTasksCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
