@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModtrektParser" as ModtrektParser LOGIC_COLOR
participant ":ListTasks\nCommandParser" as ListTasksCommandParser LOGIC_COLOR
participant ":ListTasksCommand" as ListTasksCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant "<<class>>\nArgumentTokenizer" as ArgumentTokenizer LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(cmd)
activate LogicManager

LogicManager -> ModtrektParser : parseCommand(cmd)
activate ModtrektParser

create ListTasksCommandParser
ModtrektParser -> ListTasksCommandParser
activate ListTasksCommandParser

ListTasksCommandParser --> ModtrektParser
deactivate ListTasksCommandParser

ModtrektParser -> ListTasksCommandParser : parse(flags)
activate ListTasksCommandParser

create ArgumentTokenizer
ListTasksCommandParser -> ArgumentTokenizer : isFlagPresent(flags, "-a")
activate ArgumentTokenizer

ArgumentTokenizer --> ListTasksCommandParser : showAll?
deactivate ArgumentTokenizer

create ListTasksCommand
ListTasksCommandParser -> ListTasksCommand
activate ListTasksCommand

ListTasksCommand --> ListTasksCommandParser : command
deactivate ListTasksCommand

ListTasksCommandParser --> ModtrektParser : command
deactivate ListTasksCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListTasksCommandParser -[hidden]-> ModtrektParser
destroy ListTasksCommandParser

ModtrektParser --> LogicManager : command
deactivate ModtrektParser

LogicManager -> ListTasksCommand : execute()
activate ListTasksCommand

alt -a flag is present

    ListTasksCommand -> Model : updateFilteredTaskList(SHOW_ALL_TASKS)
    activate Model

    Model --> ListTasksCommand
    deactivate Model

else else

    ListTasksCommand -> Model : updateFilteredTaskList(HIDE_ARCHIVED_TASKS)
    activate Model

    Model --> ListTasksCommand
    deactivate Model

end

create CommandResult
ListTasksCommand -> CommandResult
activate CommandResult

CommandResult --> ListTasksCommand : result
deactivate CommandResult

ListTasksCommand --> LogicManager : result
deactivate ListTasksCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
