@startuml
'https://plantuml.com/activity-diagram-beta

start
:User executes a view upcoming events command;
if () then ([input is valid])
    :Input gets parsed;
    :Creates ViewUpcomingEventsCommand;
    :Executes ViewUpcomingEventsCommand;
    :List of Events gets filtered;
    :Display success message to user;
else ([else])
    :Display error message to user;
endif
stop
@enduml
