@startuml
start
:User executes a goto command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:GoToCommandParser parses the user input;

if () then ([user input is valid]
)
:Obtain ModuleCode from user input;
:Create a new ModuleCodeMatchesKeywordPredicate from user input;
    if () then ([ModuleCode is valid]
    )
    :Obtain Module from ModuleCode;
    :Filters module list according to ModuleCodeMatchesKeywordPredicate;
    :Create a new PersonIsInModulePredicate from Module;
    :Filters person list according to PersonIsInModulePredicate;
    :Set home status to false;
    :Show success message;
    else ([else]
    )
    :Show no such module error message;
    endif
else ([else]
)
:Show error message with valid command format;
endif
stop
@enduml
