@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GoToCommandParser" as GoToCommandParser LOGIC_COLOR
participant "mc:ModuleCode" as ModuleCode LOGIC_COLOR
participant "mPred:ModuleCodeMatchesKeywordPredicate" as ModuleCodeMatchesKeywordPredicate LOGIC_COLOR
participant "command:GoToCommand" as GoToCommand LOGIC_COLOR
participant "pPred:PersonIsInModulePredicate" as PersonIsInModulePredicate LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
end box

[-> LogicManager : execute(input)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(input)
activate AddressBookParser

create GoToCommandParser
AddressBookParser -> GoToCommandParser

activate GoToCommandParser
GoToCommandParser --> AddressBookParser
deactivate GoToCommandParser

AddressBookParser -> GoToCommandParser : parse(input)

activate GoToCommandParser

create ModuleCode
GoToCommandParser -> ModuleCode
activate ModuleCode
ModuleCode --> GoToCommandParser : mc
deactivate ModuleCode

create ModuleCodeMatchesKeywordPredicate
GoToCommandParser -> ModuleCodeMatchesKeywordPredicate
activate ModuleCodeMatchesKeywordPredicate
ModuleCodeMatchesKeywordPredicate --> GoToCommandParser : mPred
deactivate ModuleCodeMatchesKeywordPredicate

create GoToCommand
GoToCommandParser -> GoToCommand
activate GoToCommand
GoToCommand --> GoToCommandParser : command
deactivate GoToCommand

GoToCommandParser --> AddressBookParser : command
deactivate GoToCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GoToCommandParser -[hidden]-> AddressBookParser
destroy GoToCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> GoToCommand : execute()

activate GoToCommand
GoToCommand -> Model : getModuleUsingModuleCode(mc)
activate Model
Model --> GoToCommand : m
deactivate Model

GoToCommand -> Model : updateFilteredModuleList(mPred)
activate Model
Model --> GoToCommand
deactivate Model

create PersonIsInModulePredicate
GoToCommand -> PersonIsInModulePredicate
activate PersonIsInModulePredicate
PersonIsInModulePredicate --> GoToCommand : pPred
deactivate PersonIsInModulePredicate

GoToCommand -> Model : updateFilteredModuleList(mPred)
activate Model
Model --> GoToCommand
deactivate Model

GoToCommand -> Model : setHomeStatus(false)
activate Model
Model --> GoToCommand
deactivate Model

create CommandResult
GoToCommand -> CommandResult
activate CommandResult

CommandResult --> GoToCommand
deactivate CommandResult

GoToCommand --> LogicManager : result
deactivate GoToCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
GoToCommand -[hidden]-> GoToCommand
destroy GoToCommand

[<--LogicManager
deactivate LogicManager
@enduml