@startuml
start
:User executes GoToCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([keyword violate the given restrictions]
)
:Show error message;
else ([else]
)
:Filters module and person list according to keyword;
:Set home status to false;
:Update GUI to show filtered module and contact list;
endif
stop
@enduml