@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PrimaryParser" as PrimaryParser LOGIC_COLOR
participant ":FindUserArgumentsParser" as FindUserArgumentsParser LOGIC_COLOR
participant "f:FindUserCommand" as FindUserCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find user alex")]
activate LogicManager

LogicManager -> PrimaryParser : parse("find user alex")
activate PrimaryParser

create FindUserArgumentsParser
PrimaryParser -> FindUserArgumentsParser
activate FindUserArgumentsParser

PrimaryParser <-- FindUserArgumentsParser
deactivate

PrimaryParser -> FindUserArgumentsParser : parse("alex")
activate FindUserArgumentsParser

create FindUserCommand
FindUserArgumentsParser -> FindUserCommand
activate FindUserCommand

FindUserArgumentsParser <-- FindUserCommand : f
deactivate FindUserCommand

PrimaryParser <-- FindUserArgumentsParser : f
deactivate FindUserArgumentsParser
PrimaryParser <[hidden]- FindUserArgumentsParser
destroy FindUserArgumentsParser

LogicManager <-- PrimaryParser : f
deactivate PrimaryParser

LogicManager -> FindUserCommand : execute()
activate FindUserCommand

FindUserCommand -> Model : updateFilteredPersonList("alex")
activate Model

FindUserCommand <-- Model
deactivate Model

create CommandResult
FindUserCommand -> CommandResult
activate CommandResult

FindUserCommand <-- CommandResult
deactivate CommandResult

LogicManager <-- FindUserCommand: result
deactivate FindUserCommand

[<-- LogicManager
deactivate LogicManager

@enduml
