@startuml
!pragma useVerticalIf on

start
:User executes SetPersonFilePathCommand;

:Verify SetPersonFilePathCommand keyword;
if() then ([else])
:show error message;
stop

else ([is valid filePath])
:Verify Index in SetPersonFilePathCommand;
if() then ([else))
:show error message;
stop

else ([valid keyword])
:Verify filePath in SetPersonFilePathCommand;
if() then ([else))
:show error message;
stop

else ([is valid filePath and Index])
:create Person Object with filePath;
:update FABook with Edited Person;
stop
@enduml
