@startuml
!include ../style.puml

package UI {
Class MainWindow UI_COLOR
Class ResidentTableView UI_COLOR
}

package Logic {
Class LogicManager LOGIC_COLOR
}

package Model {
Class ModelManager MODEL_COLOR
}

'Class MainWindow UI_COLOR
'Class LogicManager LOGIC_COLOR
'Class ModelManager MODEL_COLOR
'Class ResidentTableView UI_COLOR

MainWindow --> LogicManager
MainWindow --> ResidentTableView
LogicManager --> ModelManager

'ResidentTableView -[hidden]right-> ModelManager

@enduml
