@startuml
!include ../style.puml

Class MainWindow UI_COLOR
Class LogicManager LOGIC_COLOR
Class ModelManager MODEL_COLOR
Class ResidentTableView UI_COLOR

MainWindow --> LogicManager
MainWindow --> ResidentTableView
LogicManager --> ModelManager
@enduml
