@startuml
start
:User executes edit module command;
:ModtRekt parse the command looking for tags;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([contains all valid tags])
    :check if parameter inputs are valid;
    if () then ([valid inputs])
        :edit module in Module List;
        if () then ([Mod code is edited])
            :update associated tasks to new module code;
        endif
        :display edit success message;
    else ([else])
        :display invalid input error message;
    endif
else ([else])
    :display invalid format message;
endif
stop
@enduml
