@startuml
!pragma useVerticalIf on

start
:User presses f2;

:check a list of Person objects if any has meetings in the next 7 days;
if() then ([else])
:filtered out Person object;
stop

else ([has meetings in next 7 days])
:check filtered list for specific meeting times in the next 7 days;
if() then ([else])
:filtered out meeting times;
stop

else ([is valid filePath and Index])
:create Meeting Cards;
:fill Meeting List with Meeting Cards;
:fill Meetings Window with Meeting List;
:display Meetings Window with list of Meetings;
stop

@enduml
