@startuml
start
:User executes add
condition command;

:Model returns a filtered
list of last shown patients;

:Search for patient in the list
who matches the given index;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([patient index is valid])
    :Create a new patient using details
    from the specified patient and the
    given condition;
    :Replace the specified patient\nwith the newly created patient;
else ([else])
    :Throw CommandException;
    :UI catches CommandException;
endif
:UI displays results of command to user;
stop
@enduml
