@startuml
start
:User executes add deadline command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid format])
    :Parser parses student and deadline details;
    :Logic executes command;
    if () then ([not a duplicate deadline])
                    if () then ([new project status != "DONE"])
                        :Model executes addDeadline();
                    else ([else])
                        :UI shows error message;
                       endif
    else ([else])
        :UI shows error message;
       endif
else ([else])
    :UI shows error message;
endif
stop
@enduml
