@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddFieldCommandParser" as AddFieldCommandParser LOGIC_COLOR
participant ":AddFieldCommand" as AddFieldCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":DisplayItem" as DisplayItem MODEL_COLOR
end box

[-> LogicManager : execute()
activate LogicManager

LogicManager -> AddressBookParser : parseCommand()
activate AddressBookParser

create AddFieldCommandParser
AddressBookParser -> AddFieldCommandParser
activate AddFieldCommandParser

create AddFieldCommand
AddFieldCommandParser -> AddFieldCommand
activate AddFieldCommand

AddFieldCommand -> DisplayItem : selectFromRightModel()
activate DisplayItem

DisplayItem --> AddFieldCommand
deactivate DisplayItem

AddFieldCommand -> DisplayItem : addAttribute()
activate DisplayItem

DisplayItem --> AddFieldCommand
deactivate DisplayItem

create CommandResult
AddFieldCommand -> CommandResult
activate CommandResult

CommandResult --> AddFieldCommand
deactivate CommandResult

AddFieldCommand --> AddFieldCommandParser
deactivate AddFieldCommand

AddFieldCommandParser --> AddressBookParser
deactivate AddFieldCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

[<-- LogicManager
deactivate LogicManager


@enduml
