@startuml
!include style.puml

object "<u>:AddModuleCommand</u>" as AddModuleCommand LOGIC_COLOR
object "<u>:AddModuleCommandParser</u>" as AddModuleCommandParser LOGIC_COLOR
object "<u>:AddressBookParser</u>" as AddressBookParser LOGIC_COLOR
object "<u>:Model</u>" as Model MODEL_COLOR
object "<u>:CommandResult</u>" as CommandResult LOGIC_COLOR
object "<u>moduleToAdd:Module" as Module LOGIC_COLOR
object "<u>:ArgumentMultimap" as ArgumentMultimap LOGIC_COLOR
object "<u>:ParserUtil" as ParserUtil LOGIC_COLOR

AddressBookParser --> AddModuleCommandParser : calls
AddressBookParser --> AddModuleCommand
AddModuleCommandParser -> AddModuleCommand
AddModuleCommandParser --> ArgumentMultimap : instantiates
ParserUtil --> ArgumentMultimap : parses
AddModuleCommand --> Model
AddModuleCommand --> CommandResult : outputs
AddModuleCommand --> Module
Model -> Module : Adds
@enduml
