@startuml
!include style.puml


box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":Tuthub" as Tuthub MODEL_COLOR
participant ":UniqueTutorList" as UniqueTutorList MODEL_COLOR
end box

[-> ModelManager: addTutor(tutor)
activate ModelManager

ModelManager -> Tuthub : addTutor(tutor)
activate Tuthub

Tuthub -> UniqueTutorList: add(tutor)
activate UniqueTutorList

UniqueTutorList -> UniqueTutorList : add(tutor)
activate UniqueTutorList

UniqueTutorList --> UniqueTutorList
deactivate UniqueTutorList

UniqueTutorList --> Tuthub
deactivate UniqueTutorList

Tuthub --> ModelManager
deactivate Tuthub

ModelManager -->[
deactivate ModelManager

@enduml
