@startuml
start
:User executes add student command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid format])
    :Parser parses student details;
    :Logic executes command;
    if () then ([not a duplicate student])
        :Model executes addStudent();
    else ([else])
        :UI shows error message;
       endif
else ([else])
    :UI shows error message;
endif
stop
@enduml
