@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTagCommandParser" as AddTagCommandParser LOGIC_COLOR
participant "ParserUtil" as ParserUtil << class >> LOGIC_COLOR
participant "addTagCommand:AddTagCommand" as AddTagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute("addTag 1 st/java")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addTag 1 st/java")
activate AddressBookParser

create AddTagCommandParser
AddressBookParser -> AddTagCommandParser
activate AddTagCommandParser

AddTagCommandParser --> AddressBookParser
deactivate AddTagCommandParser

AddressBookParser -> AddTagCommandParser : parse("1 st/java")
activate AddTagCommandParser

AddTagCommandParser -> ParserUtil : parseIndex()
activate ParserUtil

ParserUtil --> AddTagCommandParser : index
deactivate ParserUtil

AddTagCommandParser -> ParserUtil : parseTags()
activate ParserUtil

ParserUtil --> AddTagCommandParser : tagMap
deactivate ParserUtil

create AddTagCommand
AddTagCommandParser -> AddTagCommand
activate AddTagCommand

AddTagCommand --> AddTagCommandParser : addTagCommand
deactivate AddTagCommand

AddTagCommandParser --> AddressBookParser : addTagCommand
deactivate AddTagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTagCommandParser -[hidden]-> AddressBookParser
destroy AddTagCommandParser

AddressBookParser --> LogicManager : addTagCommand
deactivate AddressBookParser

LogicManager -> AddTagCommand : execute()
activate AddTagCommand

AddTagCommand -> Model : getFilteredPersonList()
activate Model

Model --> AddTagCommand: personList
deactivate Model

create Person
AddTagCommand -> Person
activate Person

Person --> AddTagCommand
deactivate Person

AddTagCommand -> Model : setPerson()
activate Model

Model --> AddTagCommand
deactivate Model

create CommandResult
AddTagCommand -> CommandResult
activate CommandResult

CommandResult --> AddTagCommand
deactivate CommandResult

AddTagCommand --> LogicManager : result
deactivate AddTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
