@startuml
start
:User enters AddTask command;

if () then ([Is invalid parameter])
    :HackAssist displays \n error message indicating \n invalid user input;

else ([Is valid parameters])

    if () then ([Task already exists])
        :HackAssist displays \n error message indicating \n that Task already exist;
    else ([else])
        : Task is created;
        if () then ([user found])
             :Task assigned to \n found user based on\n task email;
        else ([user not found])
             :Error message \n indicating no \n user with that email;

           endif

        :HackAssist updates \n to display new task\n at end of the list;
    endif

endif
stop
@enduml
