@startuml
start
:User inputs Task command;

:Parses the command;

if() then ([command is valid])
    :Executes TaskCommand;
    if() then ([title and description are valid])
        :Creates a new task;
    else([invalid title or description])
        :Show parse exception error;
    endif
else([Command is missing arguments])
    :Show parse error message;
endif
stop
@enduml
