@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTagCommandParser" as AddTagCommandParser LOGIC_COLOR
participant ":AddTagCommand" as AddTagCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
end box
[-> LogicManager : execute(addL)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(addL)
activate AddressBookParser

create AddTagCommandParser
AddressBookParser -> AddTagCommandParser
activate AddTagCommandParser

AddressBookParser -> AddTagCommandParser : parse(arguments)

create AddTagCommand
AddTagCommandParser -> AddTagCommand
activate AddTagCommand

AddTagCommand --> AddTagCommandParser
deactivate AddTagCommand

AddTagCommandParser --> AddressBookParser
deactivate AddTagCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> AddTagCommand : execute()
activate AddTagCommand

AddTagCommand -> Model : setPerson()
activate Model

Model -> AddressBook : setPerson()
activate AddressBook

AddressBook --> Model :
deactivate AddressBook

Model --> AddTagCommand
deactivate Model

AddTagCommand --> LogicManager : result
deactivate AddTagCommand
AddTagCommand -[hidden]-> LogicManager : result
destroy AddTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
