@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":Logic" as Logic LOGIC_COLOR
participant ":AddTaskCommandParser" as AddTaskCommandParser LOGIC_COLOR
participant "<<class>>\nNaturalDateParser" as NaturalDateParser LOGIC_COLOR
participant "toAdd:Task" as Task LOGIC_COLOR
participant ":AddTaskCommand" as AddTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[->Logic ++
Logic -> AddTaskCommandParser **
activate AddTaskCommandParser
return

Logic -> AddTaskCommandParser ++ : parse("next thursday")
AddTaskCommandParser -> NaturalDateParser ++ : parse("next thursday")
return
AddTaskCommandParser -> Task **
activate Task
return
AddTaskCommandParser -> AddTaskCommand **
activate AddTaskCommand
return
return

Logic -> AddTaskCommand ++ : execute()
AddTaskCommand -> Model ++ : addTask(toAdd)
return
AddTaskCommand -> CommandResult **
activate CommandResult
return
return

return

@enduml
