@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskPanelParser" as TaskPanelParser LOGIC_COLOR
participant ":AddTaskCommandParser" as AddTaskCommandParser LOGIC_COLOR
participant "a:AddTaskCommand" as AddTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("task add New task")
activate LogicManager

LogicManager -> TaskPanelParser : parse("task add New task")
activate TaskPanelParser

create AddTaskCommandParser
TaskPanelParser -> AddTaskCommandParser
activate AddTaskCommandParser

AddTaskCommandParser --> TaskPanelParser
deactivate AddTaskCommandParser

TaskPanelParser -> AddTaskCommandParser : parse("New task")
activate AddTaskCommandParser

create AddTaskCommand
AddTaskCommandParser -> AddTaskCommand
activate AddTaskCommandParser

AddTaskCommand --> AddTaskCommandParser : a
deactivate AddTaskCommand

AddTaskCommandParser --> TaskPanelParser : a
deactivate AddTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTaskCommandParser -[hidden]-> TaskPanelParser
destroy AddTaskCommandParser

TaskPanelParser --> LogicManager : a
deactivate TaskPanelParser

LogicManager -> AddTaskCommand : execute()
activate AddTaskCommand

AddTaskCommand -> Model : addTask("New task")
activate Model

Model --> AddTaskCommand
deactivate Model

create CommandResult
AddTaskCommand -> CommandResult
activate CommandResult

CommandResult --> AddTaskCommand
deactivate CommandResult

AddTaskCommand --> LogicManager : result
deactivate AddTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
