@startuml
!include style.puml


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTaskCommandParser" as AddTaskCommandParser LOGIC_COLOR

participant ":AddTaskCommand" as AddTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Task" as Task MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
end box

[-> LogicManager : execute(addTask \n n/Fix toggle \n d/Fix dark mode button\n pr/high c/frontend dl/2022-12-12 \n pe/charlotte@example.com)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(commandText)
activate AddressBookParser

create AddTaskCommandParser
AddressBookParser -> AddTaskCommandParser : AddTaskCommandParser()
activate AddTaskCommandParser

AddTaskCommandParser --> AddressBookParser
deactivate AddTaskCommandParser


AddressBookParser -> AddTaskCommandParser : parse(addTask \n n/Fix toggle \n d/Fix dark mode button\n pr/high c/frontend dl/2022-12-12 \n pe/charlotte@example.com)
activate AddTaskCommandParser


AddTaskCommandParser -> AddTaskCommandParser : arePrefixesPresent()
activate AddTaskCommandParser
deactivate AddTaskCommandParser
create Task
AddTaskCommandParser -> Task
activate Task

Task --> AddTaskCommandParser
deactivate Task


create AddTaskCommand
AddTaskCommandParser -> AddTaskCommand : AddTaskCommand(task,personEmailAddress)
activate AddTaskCommand

AddTaskCommand --> AddTaskCommandParser
deactivate AddTaskCommand


AddTaskCommandParser --> AddressBookParser
deactivate AddTaskCommandParser

AddressBookParser --> LogicManager

LogicManager -> AddTaskCommand : execute()
activate AddTaskCommand

AddTaskCommand -> Model : hasTask(toAdd)
activate Model
Model --> AddTaskCommand

AddTaskCommand -> Model : addTask(task)
Model --> AddTaskCommand


AddTaskCommand -> Model : update()
Model ->AddressBook : setTasks()
activate AddressBook
AddressBook -> Model
deactivate AddressBook
Model --> AddTaskCommand
deactivate

create CommandResult
AddTaskCommand -> CommandResult
activate CommandResult

CommandResult --> AddTaskCommand
deactivate CommandResult

AddTaskCommand --> LogicManager : commandResult
deactivate AddTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
