@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InTrackParser" as InTrackParser LOGIC_COLOR
participant ":AddTaskCommandParser" as AddTaskCommandParser LOGIC_COLOR
participant "at:AddTaskCommand" as AddTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addtask 1 Technical Interview /at 25-10-2022 12:00")
activate LogicManager

LogicManager -> InTrackParser : parseCommand("addtask 1 Technical Interview /at 25-10-2022 12:00")
activate InTrackParser

create AddTaskCommandParser
InTrackParser -> AddTaskCommandParser
activate AddTaskCommandParser

AddTaskCommandParser --> InTrackParser
deactivate AddTaskCommandParser

InTrackParser -> AddTaskCommandParser : parse("1 Technical Interview /at 25-10-2022 12:00")
activate AddTaskCommandParser

create AddTaskCommand
AddTaskCommandParser -> AddTaskCommand
activate AddTaskCommand

AddTaskCommand --> AddTaskCommandParser : at
deactivate AddTaskCommand

AddTaskCommandParser --> InTrackParser : at
deactivate AddTaskCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTaskCommandParser -[hidden]-> InTrackParser
destroy AddTaskCommandParser

InTrackParser --> LogicManager : at
deactivate InTrackParser

LogicManager -> AddTaskCommand : execute()
activate AddTaskCommand

AddTaskCommand -> Model : getFilteredInternshipList()
activate Model

Model --> AddTaskCommand
deactivate Model

AddTaskCommand -> Model : setInternship(target, editedInternship)
activate Model

Model --> AddTaskCommand
deactivate Model

create CommandResult
AddTaskCommand -> CommandResult
activate CommandResult

CommandResult --> AddTaskCommand : result
deactivate CommandResult

AddTaskCommand --> LogicManager : result
deactivate AddTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
