@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeIconSize 0
show members
'https://plantuml.com/object-diagram

object "<u>John Davis:Person" as John

object "<u>:Name" as Name
object "<u>:NextofKin" as NextofKin
object "<u>:PatientType" as PatientType
object "<u>:Email" as Email
object "<u>:PastAppointment" as PastAppointment
object "<u>:Phone" as Phone

John : ...
Name : ...
Email : ...
NextofKin : ...
PatientType : ...
Phone : ...

PastAppointment : date = "12-06-2022"
PastAppointment : medication = {"paracetamol"}

John -right-> Name
John -down-> Phone
John -up-> NextofKin
John -left-> PatientType
John -up-> Email
John -down-> PastAppointment
@enduml
