@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Stage" as stage STAGE_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -[USER_COLOR]> ui : "delete 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("delete 1")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> stage : getInstance()
activate stage STAGE_COLOR

stage -[STAGE_COLOR]-> logic
deactivate stage

logic -[LOGIC_COLOR]> stage : instance.getCurrentStage()
activate stage STAGE_COLOR

stage -[STAGE_COLOR]-> logic
deactivate stage

alt Stages.HOME
    logic -[LOGIC_COLOR]> model : deleteItinerary(i)
    activate model MODEL_COLOR

    model -[MODEL_COLOR]-> logic
    deactivate model
else Stages.PLAN
    logic -[LOGIC_COLOR]> model : deleteItem(i)
    activate model MODEL_COLOR

    model -[MODEL_COLOR]-> logic
    deactivate model
end

logic -[LOGIC_COLOR]> storage : saveWaddle(waddle)
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to file
activate storage STORAGE_COLOR_T1
storage --[STORAGE_COLOR]> storage
deactivate storage

storage --[STORAGE_COLOR]> logic
deactivate storage

logic --[LOGIC_COLOR]> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui
@enduml
