@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor BLACK

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Logic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class Model MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI --> Logic
UI -right-> Model
Logic --> Storage
Logic -down-> Model
Main --> UI
Main --> Logic
Main --> Storage
Main -up-> Model
Main -down-> Commons

Storage -up.> Model
Storage .right.>File
User ..> UI
@enduml
