@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor BLACK

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR
Participant ":Storage" as storage STORAGE_COLOR

user -> ui : "delete 1"
activate ui

ui -> logic : execute("delete 1")
activate logic

logic -> model : deleteResident(p)
activate model

model --> logic
deactivate model

logic -> storage : saveResidentBook(residentBook)
activate storage

storage -> storage : Save to file
activate storage
storage --> storage
deactivate storage

storage --> logic
deactivate storage

logic -> storage : saveVenueBook(venueBook)
activate storage

storage -> storage : Save to file
activate storage
storage --> storage
deactivate storage

storage --> logic
deactivate storage

logic --> ui
deactivate logic

ui--> user
deactivate ui
@enduml
