@startuml

skinparam sequence {
 ActorFontColor black
 ParticipantFontColor white
}

actor User as User #black
participant ":UI" as UI #green
participant ":Logic" as Logic #3333C4
participant ":Model" as Model #9D0011
participant ":Storage" as Storage #A4760A

User->UI : "rm CS2103"
activate UI #green

UI->Logic : execute("rm CS2103")
activate Logic #3333C4

Logic->Model : deleteUserModule("CS2103")
activate Model #9D0011

Model-->Logic
deactivate Model

Logic->Storage : saveUserModuleList(userModuleList)
activate Storage #A4760A

Storage->Storage : Save to file
activate Storage #FEE373

Storage-->Storage
deactivate Storage

Storage-->Logic
deactivate Storage

Logic-->UI
deactivate Logic

UI-->User
deactivate UI




@enduml