@startuml

skinparam defaultFontSize 20;

start
:User executes AssignPolicyCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then
    :Throw CommandException
    with invalid command
    message;
else ([ValidSyntax])

if () then
    : Throw CommandException
     (invalid person index);
else ([Person index exists in person list])
    if () then
    : Throw CommandException
     (invalid policy index);
    else ([Policy index exists in policy list])
    : Retrieve relevant person
     and policy;
    : Attempt to addPolicy;
    if () then
    : Display assign success message;
    else ([Person already has that policy assigned])
    : Display assign failure message;
    endif
    endif
endif
stop
@enduml
