@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "c:AssignCommand" as AssignCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "student:Student" as Student MODEL_COLOR
participant "newStudent:Student" as NewStudent MODEL_COLOR
end box

[-> AssignCommand: execute(model)
activate AssignCommand

AssignCommand -> Model: getFilteredStudentList()
activate Model
Model --> AssignCommand: students
deactivate Model

loop for each student to be assigned
    AssignCommand -> Student: addModuleClass(moduleClassToAssign)
    activate Student

    create NewStudent
    Student -> NewStudent
    activate NewStudent

    NewStudent --> Student
    deactivate NewStudent

    Student --> AssignCommand: newStudent
    deactivate Student

    AssignCommand -> Model: setStudent(student, newStudent)
    activate Model

    Model --> AssignCommand
    deactivate Model
end

create CommandResult
AssignCommand -> CommandResult
activate CommandResult

CommandResult --> AssignCommand
deactivate CommandResult

AssignCommand -->[: result
deactivate AssignCommand

@enduml
