@startuml

title AssignTaskCommand

start
:User executes "assigntask" command;
:Command is parsed;

if () then ([parameters are parsed correctly])
    :Executes;
    if () then ([group and person exist in TABS])
    :Obtain group and person from Model;
        if () then ([person is a member of group])
        :Check person's assignment list;
            if () then ([person does not have assignment])
            :AssignTaskCommand performs assignment of task;
            :Return CommandResult to LogicManager;
            else ([else])
            :Throw CommandException indicating person has duplicate task;
            endif
        else ([else])
        :Throw CommandException indicating person not a member;
        endif
    else ([else])
    :Throw CommandException for missing group/person;
    endif
else ([else])
: Throw ParseException;
endif

stop

@enduml
