@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AttendanceCommandParser" as AttendanceCommandParser LOGIC_COLOR
participant "a:AttendanceCommand" as AttendanceCommand LOGIC_COLOR
end box

[-> LogicManager : execute("attendance 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("attendance 1")
activate AddressBookParser

create AttendanceCommandParser
AddressBookParser -> AttendanceCommandParser
activate AttendanceCommandParser

AttendanceCommandParser --> AddressBookParser
deactivate AttendanceCommandParser

AddressBookParser -> AttendanceCommandParser : parse("1")
activate AttendanceCommandParser

create AttendanceCommand
AttendanceCommandParser -> AttendanceCommand
activate AttendanceCommand

AttendanceCommand --> AttendanceCommandParser : a
deactivate AttendanceCommand

AttendanceCommandParser --> AddressBookParser : a
deactivate AttendanceCommandParser

AttendanceCommandParser -[hidden]-> AddressBookParser
destroy AttendanceCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

ref over LogicManager : execute attendance command

[<--LogicManager
deactivate LogicManager
@enduml
