@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

PropertyDirectory *-right-> "1" UniquePropertyList
PropertyDirectory *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePropertyList
UniqueTagList -[hidden]down- UniquePropertyList

UniqueTagList *-right-> "*" Tag
UniquePropertyList -right-> Property

Property -up-> "*" Tag

Property *--> Name
Property *--> Address
Property *--> Price
Property *--> Status
Property *--> Type
@enduml
