@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

HobbyList *-right-> "1" UniqueActivityList
HobbyList *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueActivityList
UniqueTagList -[hidden]down- UniqueActivityList

UniqueTagList *-right-> "*" Tag
UniqueActivityList -right-> Activity

Activity -up-> "*" Tag

Activity *--> Name
Activity *--> Description
Activity *--> Date
@enduml
