@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package Calendar_Ui <<Rectangle>>{
Class "{abstract}\nUiPart" as UiPart
Class CalendarDisplay
Class "{abstract}\nCalendarButton" as CalendarButton
Class EventButton
Class NextButton
Class PreviousButton
Class JumpText
Class CalendarEventListPanel
Class TextValidation
Class CalendarPopup
Class CalendarPopupContent
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class CalendarLogic
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> CalendarDisplay

CalendarDisplay -down-> "*" CalendarEventListPanel
CalendarDisplay -down-> "1" NextButton
CalendarDisplay -down-> "1" PreviousButton
CalendarDisplay -down-> "1" JumpText
CalendarDisplay -down-> "1" TextValidation
CalendarEventListPanel -down-> "*" EventButton

EventButton "1" <-down-> "1" CalendarPopup
EventButton -down|> CalendarButton
NextButton -down-|> CalendarButton
PreviousButton -down-|> CalendarButton
CalendarPopup -right> "1" CalendarPopupContent
CalendarDisplay -right-> CalendarLogic

CalendarDisplay --|> UiPart
CalendarButton --|> UiPart
JumpText ---|> UiPart
TextValidation --|> UiPart
CalendarPopup --|> UiPart
CalendarPopupContent -|> UiPart


CalendarButton ..> Model
JumpText ..> Model
TextValidation ..> Model

CalendarDisplay -[hidden]up- NextButton

@enduml
