@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam linetype ortho
hide empty methods
hide empty members


title Final state after executing the <plain><font:monospaced><back:lightgray>ClearDebtsCommand</back></font></plain>

package Model {

class NewPerson as "__newPerson1:Person__"
    class NewDebtList as "__newList:DebtList__"

}




NewPerson --> NewDebtList


@end
