@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as logic LOGIC_COLOR
participant ":TuthubParser" as parser LOGIC_COLOR
participant ":CommentCommandParser" as cp LOGIC_COLOR
participant ":CommentCommand" as cc LOGIC_COLOR
participant ":CommandResult" as result LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as model MODEL_COLOR
participant ":Tutor" as tutor MODEL_COLOR
participant ":CommentList" as comments MODEL_COLOR
participant ":Comment" as comment MODEL_COLOR
end box

[-> logic: execute("comment 1 c/Often late")

activate logic
logic -> parser: parseCommand("comment 1 c/Often late")

activate parser
create cp
parser -> cp: parse("1 c/Often late")

activate cp
create cc
cp -> cc

activate cc
create comment
cc -> comment

activate comment
comment --> cc: Comment
deactivate comment

cc --> cp: CommentCommand
deactivate cc

cp --> parser: CommentCommand
destroy cp

parser --> logic: CommentCommand
deactivate parser

logic -> cc: execute()
activate cc
cc -> model :getFilteredTutorList()

activate model
create tutor
model -> tutor

activate tutor
create comments
tutor -> comments: getComments()
activate comments

comments -> comments: addComment(Comment)

comments --> tutor
deactivate comments

tutor --> model
deactivate tutor

model --> cc
deactivate model

create result
cc -> result

activate result
result --> cc: result
deactivate result

cc --> logic: result
destroy cc

[<-- logic: result
@enduml
