@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits FoodGuide])
    :Purge redundant states;
    :Save FoodGuide to
    foodGuideStateList;
else ([else])
endif
stop
@enduml
