@startuml
'https://plantuml.com/activity-diagram-beta

start
:on key press;

' extra spaces used for formatting
switch ()
case (  [key press is "UP"])
  :getPreviousCommand();
case (  [key press is "DOWN"])
    :getNextCommand();
case (  [else])
    stop
    note right
        Treat the 2 end nodes
        as 1 end node.
    end note
endswitch

:textField:setText(command);
label ending
stop

@enduml
