@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits Friday])
    :Purge redundant states;
    :Save Friday to
    fridayStateList;
else ([else])
endif
stop
@enduml
