@startuml
!include style.puml
skinparam arrowThickness 1.1

package Logic {
Class "<<interface>>\nLogic" as Logic LOGIC_COLOR
Class LogicManager LOGIC_COLOR
}

package Model{
Class "<<interface>>\nModel" as Model MODEL_COLOR
Class ModelManager MODEL_COLOR
}

package Storage{
Class "<<interface>>\nStorage" as Storage STORAGE_COLOR
Class StorageManager STORAGE_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
ModelManager .up.|> Model
StorageManager .up.|> Storage

LogicManager --> Model
LogicManager --> Storage
@enduml
