@startuml
!include style.puml
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RDeleteCommandParser" as RDeleteCommandParser LOGIC_COLOR
participant ":RDeleteCommand" as RDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("rdel 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("rdel 1")
activate AddressBookParser

create RDeleteCommandParser
AddressBookParser -> RDeleteCommandParser
activate RDeleteCommandParser

RDeleteCommandParser --> AddressBookParser: :RDeleteCommandParser
deactivate RDeleteCommandParser

AddressBookParser -> RDeleteCommandParser : parse("1")
activate RDeleteCommandParser

create RDeleteCommand
RDeleteCommandParser -> RDeleteCommand : RDeleteCommand(Index)
activate RDeleteCommand

RDeleteCommand --> RDeleteCommandParser : :RDeleteCommand
deactivate RDeleteCommand

RDeleteCommandParser --> AddressBookParser : :RDeleteCommand
deactivate RDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
RDeleteCommandParser -[hidden]-> AddressBookParser
destroy RDeleteCommandParser

AddressBookParser --> LogicManager : :RDeleteCommand
deactivate AddressBookParser

LogicManager -> RDeleteCommand : execute()
activate RDeleteCommand

RDeleteCommand -> Model : deleteReview(reviewToDelete)
activate Model

Model --> RDeleteCommand
deactivate Model

create CommandResult
RDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> RDeleteCommand : :CommandResult
deactivate CommandResult

RDeleteCommand --> LogicManager : :CommandResult
deactivate RDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
