@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteNoteCommandParser" as DeleteNoteCommandParser LOGIC_COLOR
participant "d:DeleteNoteCommand" as DeleteNoteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteNote 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteNote 1")
activate AddressBookParser

create DeleteNoteCommandParser
AddressBookParser -> DeleteNoteCommandParser
activate DeleteNoteCommandParser

DeleteNoteCommandParser --> AddressBookParser
deactivate DeleteNoteCommandParser

AddressBookParser -> DeleteNoteCommandParser : parse("1")
activate DeleteNoteCommandParser

create DeleteNoteCommand
DeleteNoteCommandParser -> DeleteNoteCommand
activate DeleteNoteCommand

DeleteNoteCommand --> DeleteNoteCommandParser : d
deactivate DeleteNoteCommand

DeleteNoteCommandParser --> AddressBookParser : d
deactivate DeleteNoteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteNoteCommandParser -[hidden]-> AddressBookParser
destroy DeleteNoteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteNoteCommand : execute()
activate DeleteNoteCommand

DeleteNoteCommand -> Model : getAddressBook()
activate Model

Model --> DeleteNoteCommand
deactivate Model

DeleteNoteCommand -> Model : deleteNote(noteToDelete)
activate Model

Model --> DeleteNoteCommand
deactivate Model

create CommandResult
DeleteNoteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteNoteCommand
deactivate CommandResult

DeleteNoteCommand --> LogicManager : result
deactivate DeleteNoteCommand



[<--LogicManager
deactivate LogicManager
@enduml
