@startuml
start
:User executes delete command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([index is valid])
    :Delete person at
    specified index;
    :Update UI to display
    updated contact list;
else ([else])
    if () then ([name prefix is present])
            if () then ([name occurs once])
                :Delete person with
                specified name;
                :Update UI to display
                updated contact list;
            else ([else])
                if () then ([name occurs more than once])
                    :Show error message
                    saying name occurs
                    more than once;
                else ([name does not occur])
                    :Show error message
                    saying name is invalid;
                endif
            endif
    else ([else])
        :Show error message
        saying index is invalid;
    endif
endif
stop
@enduml
