@startuml
start
:User executes rdel command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
if () then ([Command is Valid])
    :FoodWhere deletes the [Review] at given index;
else ([else])
endif
stop
@enduml
