@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteReminderCommandParser" as DeleteReminderCommandParser LOGIC_COLOR
participant "d:DeleteReminderCommand" as DeleteReminderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteR 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteR 1")
activate AddressBookParser

create DeleteReminderCommandParser
AddressBookParser -> DeleteReminderCommandParser
activate DeleteReminderCommandParser

DeleteReminderCommandParser --> AddressBookParser
deactivate DeleteReminderCommandParser

AddressBookParser -> DeleteReminderCommandParser : parse("1")
activate DeleteReminderCommandParser

create DeleteReminderCommand
DeleteReminderCommandParser -> DeleteReminderCommand
activate DeleteReminderCommand

DeleteReminderCommand --> DeleteReminderCommandParser : d
deactivate DeleteReminderCommand

DeleteReminderCommandParser --> AddressBookParser : d
deactivate DeleteReminderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteReminderCommandParser -[hidden]-> AddressBookParser
destroy DeleteReminderCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteReminderCommand : execute()
activate DeleteReminderCommand

DeleteReminderCommand -> Model : deleteReminder(1)
activate Model

Model --> DeleteReminderCommand
deactivate Model

create CommandResult
DeleteReminderCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteReminderCommand
deactivate CommandResult

DeleteReminderCommand --> LogicManager : result
deactivate DeleteReminderCommand

[<--LogicManager
deactivate LogicManager
@enduml