@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteEventCommandParser" as DeleteEventCommandParser LOGIC_COLOR
participant "a:DeleteEventCommand" as DeleteEventCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "b:ModelManager" as ModelManager MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":UniqueEventList" as UniqueEventList MODEL_COLOR
end box

-> LogicManager : execute(cmd)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(cmd)
activate AddressBookParser

create DeleteEventCommandParser
AddressBookParser -> DeleteEventCommandParser : parse(cmd)
activate DeleteEventCommandParser

create DeleteEventCommand
DeleteEventCommandParser -> DeleteEventCommand
activate DeleteEventCommand

DeleteEventCommand --> DeleteEventCommandParser : a
deactivate DeleteEventCommand

DeleteEventCommandParser --> AddressBookParser : a
deactivate DeleteEventCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser
destroy DeleteEventCommandParser

LogicManager -> DeleteEventCommand : execute(b)
activate DeleteEventCommand

DeleteEventCommand -> ModelManager : deleteEvent(event)
activate ModelManager

ModelManager -> AddressBook : deleteEvent(event)
activate AddressBook

AddressBook -> UniqueEventList : remove(event)
activate UniqueEventList

UniqueEventList --> AddressBook
deactivate UniqueEventList

AddressBook --> ModelManager
deactivate AddressBook

ModelManager --> DeleteEventCommand
deactivate ModelManager

DeleteEventCommand --> LogicManager : CommandResult
deactivate DeleteEventCommand

<--LogicManager
deactivate LogicManager
destroy DeleteEventCommand

@enduml
