@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HealthContactParser" as HealthContactParser LOGIC_COLOR
participant ":DeleteAppointmentCommandParser" as DeleteAppointmentCommandParser LOGIC_COLOR
participant "d:DeleteAppointmentCommand" as DeleteAppointmentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteappointment 1")
activate LogicManager

LogicManager -> HealthContactParser : parseCommand("deleteappointment 1")
activate HealthContactParser

create DeleteAppointmentCommandParser
HealthContactParser -> DeleteAppointmentCommandParser
activate DeleteAppointmentCommandParser

DeleteAppointmentCommandParser --> HealthContactParser
deactivate DeleteAppointmentCommandParser

HealthContactParser -> DeleteAppointmentCommandParser : parse("1")
activate DeleteAppointmentCommandParser

create DeleteAppointmentCommand
DeleteAppointmentCommandParser -> DeleteAppointmentCommand
activate DeleteAppointmentCommand

DeleteAppointmentCommand --> DeleteAppointmentCommandParser : d
deactivate DeleteAppointmentCommand

DeleteAppointmentCommandParser --> HealthContactParser : d
deactivate DeleteAppointmentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteAppointmentCommandParser -[hidden]-> HealthContactParser
destroy DeleteAppointmentCommandParser

HealthContactParser --> LogicManager : d
deactivate HealthContactParser

LogicManager -> DeleteAppointmentCommand : execute()
activate DeleteAppointmentCommand

DeleteAppointmentCommand -> Model : deleteAppointment(appointmentToDelete)
activate Model

Model --> DeleteAppointmentCommand
deactivate Model

create CommandResult
DeleteAppointmentCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteAppointmentCommand
deactivate CommandResult

DeleteAppointmentCommand --> LogicManager : result
deactivate DeleteAppointmentCommand

[<--LogicManager
deactivate LogicManager
@enduml