@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":Parser" as Parser LOGIC_COLOR
participant "d:DeletePersonCommand" as DeletePersonCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete-person 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete-person 1")
activate AddressBookParser

create Parser
AddressBookParser -> Parser
activate Parser

Parser --> AddressBookParser
deactivate Parser

AddressBookParser -> Parser : parse("1")
activate Parser

create DeletePersonCommand
Parser -> DeletePersonCommand
activate DeletePersonCommand

DeletePersonCommand --> Parser : d
deactivate DeletePersonCommand

Parser --> AddressBookParser : d
deactivate Parser
'Hidden arrow to position the destroy marker below the end of the activation bar.
Parser -[hidden]-> AddressBookParser
destroy Parser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeletePersonCommand : execute()
activate DeletePersonCommand

DeletePersonCommand -> Model : deletePerson(1)
activate Model

Model --> DeletePersonCommand
deactivate Model

create CommandResult
DeletePersonCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePersonCommand
deactivate CommandResult

DeletePersonCommand --> LogicManager : result
destroy DeletePersonCommand

[<--LogicManager
deactivate LogicManager
@enduml
