@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":UninurseBookParser" as UninurseBookParser LOGIC_COLOR
participant ":DeletePatientCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeletePatientCommand" as DeletePatientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> UninurseBookParser : parseCommand("delete 1")
activate UninurseBookParser

create DeleteCommandParser
UninurseBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> UninurseBookParser
deactivate DeleteCommandParser

UninurseBookParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeletePatientCommand
DeleteCommandParser -> DeletePatientCommand
activate DeletePatientCommand

DeletePatientCommand --> DeleteCommandParser : d
deactivate DeletePatientCommand

DeleteCommandParser --> UninurseBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> UninurseBookParser
destroy DeleteCommandParser

UninurseBookParser --> LogicManager : d
deactivate UninurseBookParser

LogicManager -> DeletePatientCommand : execute()
activate DeletePatientCommand

DeletePatientCommand -> Model : deletePerson(1)
activate Model

Model --> DeletePatientCommand
deactivate Model

create CommandResult
DeletePatientCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePatientCommand
deactivate CommandResult

DeletePatientCommand --> LogicManager : result
deactivate DeletePatientCommand

[<--LogicManager
deactivate LogicManager
@enduml
