@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HealthContactParser" as HealthContactParser LOGIC_COLOR
participant ":DeleteBillCommandParser" as DeleteBillCommandParser LOGIC_COLOR
participant "d:DeleteBillCommand" as DeleteBillCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deletebill 1")
activate LogicManager

LogicManager -> HealthContactParser : parseCommand("deletebill 1")
activate HealthContactParser

create DeleteBillCommandParser
HealthContactParser -> DeleteBillCommandParser
activate DeleteBillCommandParser

DeleteBillCommandParser --> HealthContactParser
deactivate DeleteBillCommandParser

HealthContactParser -> DeleteBillCommandParser : parse("1")
activate DeleteBillCommandParser

create DeleteBillCommand
DeleteBillCommandParser -> DeleteBillCommand
activate DeleteBillCommand

DeleteBillCommand --> DeleteBillCommandParser : d
deactivate DeleteBillCommand

DeleteBillCommandParser --> HealthContactParser : d
deactivate DeleteBillCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteBillCommandParser -[hidden]-> HealthContactParser
destroy DeleteBillCommandParser

HealthContactParser --> LogicManager : d
deactivate HealthContactParser

LogicManager -> DeleteBillCommand : execute()
activate DeleteBillCommand

DeleteBillCommand -> Model : deleteBill(billToDelete)
activate Model

Model --> DeleteBillCommand
deactivate Model

create CommandResult
DeleteBillCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteBillCommand
deactivate CommandResult

DeleteBillCommand --> LogicManager : result
deactivate DeleteBillCommand

[<--LogicManager
deactivate LogicManager
@enduml
