@startuml
!include style.puml


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteTaskCommandParser" as DeleteTaskCommandParser LOGIC_COLOR

participant ":DeleteTaskCommand" as DeleteTaskCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Task" as Task MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":Person" as Person MODEL_COLOR
end box

[-> LogicManager : execute(DeleteTask 1)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(commandText)
activate AddressBookParser

create DeleteTaskCommandParser
AddressBookParser -> DeleteTaskCommandParser : DeleteTaskCommandParser()
activate DeleteTaskCommandParser
DeleteTaskCommandParser --> AddressBookParser
deactivate DeleteTaskCommandParser


AddressBookParser -> DeleteTaskCommandParser : parse(DeleteTask 1)
activate DeleteTaskCommandParser

create DeleteTaskCommand
DeleteTaskCommandParser -> DeleteTaskCommand : DeleteTaskCommand(index)
activate DeleteTaskCommand
DeleteTaskCommand --> DeleteTaskCommandParser
deactivate DeleteTaskCommand
DeleteTaskCommandParser --> AddressBookParser
deactivate DeleteTaskCommandParser

AddressBookParser --> LogicManager

LogicManager -> DeleteTaskCommand : execute()
activate DeleteTaskCommand

DeleteTaskCommand -> Model : getFilteredTaskList()
activate Model
Model --> DeleteTaskCommand

DeleteTaskCommand -> Model : getFilteredPeopleList()
Model --> DeleteTaskCommand

DeleteTaskCommand -> Person : getEmail()
activate Person
Person --> DeleteTaskCommand
deactivate Person

DeleteTaskCommand -> Model : deleteTask(task)
Model --> DeleteTaskCommand


DeleteTaskCommand -> Model : update()
Model ->AddressBook : setTasks()
activate AddressBook
AddressBook -> Model
deactivate AddressBook
Model --> DeleteTaskCommand
deactivate

create CommandResult
DeleteTaskCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteTaskCommand
deactivate CommandResult

DeleteTaskCommand --> LogicManager : commandResult
deactivate DeleteTaskCommand

[<--LogicManager
deactivate LogicManager
@enduml
