@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":Indexes" as Indexes LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1 3")
activate LogicManager

LogicManager -> InternshipBookParser : parseCommand("delete 1 3")
activate InternshipBookParser

create DeleteCommandParser
InternshipBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> InternshipBookParser
deactivate DeleteCommandParser

InternshipBookParser -> DeleteCommandParser : parse("1 3")
activate DeleteCommandParser

create Indexes
DeleteCommandParser -> Indexes
activate Indexes
Indexes --> DeleteCommandParser
deactivate Indexes
create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> InternshipBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> InternshipBookParser
destroy DeleteCommandParser

InternshipBookParser --> LogicManager : d
deactivate InternshipBookParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Indexes
activate Indexes

Indexes --> DeleteCommand: toDelete
deactivate Indexes
Indexes -[hidden]-> DeleteCommand: toDelete
destroy Indexes
DeleteCommand -> Model : deleteInternship(toDelete)
activate Model

Model --> DeleteCommand
deactivate Model


DeleteCommand --> LogicManager : result
deactivate DeleteCommand
DeleteCommand -[hidden]-> LogicManager : result
destroy DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
