@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MyInsuRecParser" as MyInsuRecParser LOGIC_COLOR
participant "l:ListMeetingCommand" as ListMeetingCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

[->MainWindow : executeCommand("listMeeting")
activate MainWindow

group ref [execute ListMeetingCommand]

end

MainWindow -> CommandResult : getCommandSpecific()
activate CommandResult

CommandResult --> MainWindow : XYZSpecific
deactivate CommandResult

MainWindow --> MainWindow : setListPanelToXYZSpecific()

[<--MainWindow
deactivate MainWindow
@enduml
