@startuml
start
:User enters Edit command;

if () then ([Is invalid parameter])
    : TrackAScholar displays \nerror message indicating \ninvalid user input;

else ([Is valid parameters])

    if () then ([Valid index])
        :Retrieve current applicant\n    from TrackAScholar;

        :Create an edited applicant \nwith input given by the user;

        if () then ([Edited applicant already\n exist in TrackAScholar])
            :TrackAScholar displays \nerror message indicating \nthat Applicant already exist;

        else ([else])
            :Replaces current applicant\n     with edited applicant;

            :TrackAScholar updates \nto display edited applicant;
        endif

    else ([else])
        :TrackAScholar displays \nerror message indicating \nindex provided is invalid;

    endif

endif
stop
@enduml
