@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditInternshipCommandParser" as EditInternshipCommandParser LOGIC_COLOR
participant "e:EditInternshipCommand" as EditInternshipCommand LOGIC_COLOR
participant "d:EditInternshipCommandDescriptor" as EditInternshipCommandDescriptor LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Internship" as Internship MODEL_COLOR
end box

[-> LogicManager : execute("edit -i 1 s/R")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit -i 1 s/R")
activate AddressBookParser

create EditInternshipCommandParser
AddressBookParser -> EditInternshipCommandParser
activate EditInternshipCommandParser

EditInternshipCommandParser --> AddressBookParser
deactivate EditInternshipCommandParser

AddressBookParser -> EditInternshipCommandParser : parse("1 s/R")
activate EditInternshipCommandParser

create EditInternshipCommandDescriptor
EditInternshipCommandParser -> EditInternshipCommandDescriptor : EditInternshipCommandDescriptor()
activate EditInternshipCommandDescriptor
EditInternshipCommandDescriptor --> EditInternshipCommandParser : descriptor
deactivate EditInternshipCommandDescriptor

EditInternshipCommandParser -> EditInternshipCommandDescriptor : setInternshipStatus()
activate EditInternshipCommandDescriptor
EditInternshipCommandDescriptor --> EditInternshipCommandParser
deactivate EditInternshipCommandDescriptor


create EditInternshipCommand
EditInternshipCommandParser -> EditInternshipCommand : EditInternshipCommand(1, d)
activate EditInternshipCommand


EditInternshipCommand --> EditInternshipCommandParser : command
deactivate EditInternshipCommand

EditInternshipCommandParser --> AddressBookParser : command
deactivate EditInternshipCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditInternshipCommandParser -[hidden]-> AddressBookParser
destroy EditInternshipCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> EditInternshipCommand : execute()
activate EditInternshipCommand

EditInternshipCommand -> Model : updateFilteredPersonList()
activate Model
Model -> Model : getFilteredInternshipList()
Model --> EditInternshipCommand : internshipToEdit
deactivate Model

create Internship
EditInternshipCommand -> Internship
activate Internship
Internship --> EditInternshipCommand : editedInternship
deactivate Internship


EditInternshipCommand -> Model : setInternship(internshipToEdit, editedInternship)
activate Model
Model --> EditInternshipCommand
deactivate Model

EditInternshipCommand -> Model : updateFilteredInternshipList()
activate Model
Model --> EditInternshipCommand
deactivate Model

create CommandResult
EditInternshipCommand -> CommandResult
activate CommandResult

CommandResult --> EditInternshipCommand : result
deactivate CommandResult

EditInternshipCommand --> LogicManager : result
deactivate EditInternshipCommand

[<--LogicManager
deactivate LogicManager
@enduml
