@startuml
start
:User executes redit command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
if () then ([Command is Valid])
    :FoodWhere edits the [Review];
else ([else])
endif
stop
@enduml
