@startuml
start
repeat
:User enters edit person command;
  if () then ([date of birth format is valid])
    if () then ([person already exists
    in the contact list])
      :Person is edited with new date of birth field;
      stop
    else ([else])
    endif
  else ([else])
  endif
backward :System shows error message;
repeat while;
@enduml
