@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([invalid arguments])
    :Display error message;
else ([else])
    : CodeConnect edits the task;
endif

stop
@enduml
