@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditLoanCommandParser" as EditLoanCommandParser LOGIC_COLOR
participant "d:EditLoanCommand" as EditLoanCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("editLoan 1 amt/10 reason/logistics")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("editLoan 1 amt/10 reason/logistics")
activate AddressBookParser

create EditLoanCommandParser
AddressBookParser -> EditLoanCommandParser
activate EditLoanCommandParser

EditLoanCommandParser --> AddressBookParser
deactivate EditLoanCommandParser

AddressBookParser -> EditLoanCommandParser : parse("1 amt/10 reason/logistics")
activate EditLoanCommandParser

create EditLoanCommand
EditLoanCommandParser -> EditLoanCommand
activate EditLoanCommand

EditLoanCommand --> EditLoanCommandParser : d
deactivate EditLoanCommand

EditLoanCommandParser --> AddressBookParser : d
deactivate EditLoanCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditLoanCommandParser -[hidden]-> AddressBookParser
destroy EditLoanCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> EditLoanCommand : execute()
activate EditLoanCommand

EditLoanCommand -> Model : deletePerson(1)
activate Model

Model --> EditLoanCommand
deactivate Model

create CommandResult
EditLoanCommand -> CommandResult
activate CommandResult

CommandResult --> EditLoanCommand
deactivate CommandResult

EditLoanCommand --> LogicManager : result
deactivate EditLoanCommand

[<--LogicManager
deactivate LogicManager
@enduml
