@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditEventCommandParser" as EditEventCommandParser LOGIC_COLOR
participant "e:EditEventCommand" as EditEventCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "b:ModelManager" as ModelManager MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":UniqueEventList" as UniqueEventList MODEL_COLOR
end box

-> LogicManager : execute(cmd)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(cmd)
activate AddressBookParser

create EditEventCommandParser
AddressBookParser -> EditEventCommandParser : parse(cmd)
activate EditEventCommandParser

create EditEventCommand
EditEventCommandParser -> EditEventCommand
activate EditEventCommand

EditEventCommand --> EditEventCommandParser : e
deactivate EditEventCommand

EditEventCommandParser --> AddressBookParser : e
deactivate EditEventCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser
destroy EditEventCommandParser

LogicManager -> EditEventCommand : execute(b)
activate EditEventCommand

EditEventCommand -> ModelManager : setEvent(E1, E2)
activate ModelManager

ModelManager -> AddressBook : setEvent(E1, E2)
activate AddressBook

AddressBook -> UniqueEventList : setEvent(E1, E2)
activate UniqueEventList

UniqueEventList --> AddressBook
deactivate UniqueEventList

AddressBook --> ModelManager
deactivate AddressBook

ModelManager --> EditEventCommand
deactivate ModelManager

EditEventCommand --> LogicManager : CommandResult
deactivate EditEventCommand

<--LogicManager
deactivate LogicManager
destroy EditEventCommand
@enduml
