@startuml
skinparam activity {
    ArrowColor #A80036
    BackgroundColor #FEFECE
    BorderColor #A80036
    BorderThickness 1.5
}
start
:User executes edit command;
:Get guest to edit;
:Create new guest using fields provided;
:Set new guest to model;
stop

@enduml
