@startuml
start
:User executes command;
:Parse Command;
if () then ([Edited fields are valid and command is valid])
  if () then([Index < 0, Index < 2147483648
  and module exist
  if module field is to be edited])
      if () then([module field is edited and exam is linked to task])
          :Unlink tasks from exam
           and replace exam with edited exam.;
          : Display message saying exam is edited successfully
          with a warning that says that tasks previously linked
           to exam are now unlinked to the exam.;
      else([else])
          :Replace exam with edited exam.
           The exam field in the task will also be updated
           for tasks that are linked to the exam.;
          :Display message saying that exam is successfully edited;
      endif
  else([else])
     :Display error message;
  endif
else ([else])
  :Display error message regarding invalid fields
  or invalid command;

endif

stop

@enduml
