@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ExportCommandParser" as ExportCommandParser LOGIC_COLOR
participant "ex:ExportCommand" as ExportCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":ModelManager" as ModelManager LOGIC_COLOR
participant ":CsvUtils" as CsvUtils LOGIC_COLOR
end box

[-> LogicManager : execute("export mycontacts")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("export mycontacts")
activate AddressBookParser

create ExportCommandParser
AddressBookParser -> ExportCommandParser
activate ExportCommandParser

ExportCommandParser -> AddressBookParser
deactivate ExportCommandParser

AddressBookParser -> ExportCommandParser : parse("mycontacts")
activate ExportCommandParser

create ExportCommand
ExportCommandParser -> ExportCommand : ExportCommand(fileName)
activate ExportCommand


ExportCommand --> ExportCommandParser : ex
deactivate ExportCommand

ExportCommandParser --> AddressBookParser : ex
deactivate ExportCommandParser

ExportCommandParser -[hidden]-> AddressBookParser
destroy ExportCommandParser

AddressBookParser --> LogicManager : ex
deactivate AddressBookParser

LogicManager -> ExportCommand : execute()
activate ExportCommand

ExportCommand -> ModelManager : getAddressBookFilePath()
activate ModelManager

ModelManager -> ExportCommand : addressBookFilePath
deactivate ModelManager

ExportCommand -> CsvUtils : exportAsCsv(addressBookFilePath, fileName)
activate CsvUtils

CsvUtils --> ExportCommand
deactivate CsvUtils
create CommandResult
ExportCommand -> CommandResult
activate CommandResult

CommandResult --> ExportCommand
deactivate CommandResult

ExportCommand --> LogicManager
deactivate ExportCommand

[<--LogicManager
deactivate LogicManager
@enduml
