@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaAssistParser" as TaAssistParser LOGIC_COLOR
participant "e:ExportCommand" as ExportCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
participant "action:ExportCsvStorageAction" as ExportCsvStorageAction LOGIC_COLOR
participant "finalResult:CommandResult" as CommandResult2 LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR
end box

[-> LogicManager : execute("export")
activate LogicManager

LogicManager -> TaAssistParser : parseCommand("export")
activate TaAssistParser

create ExportCommand
TaAssistParser -> ExportCommand
activate ExportCommand

ExportCommand --> TaAssistParser : e
deactivate ExportCommand

TaAssistParser --> LogicManager : e
deactivate TaAssistParser

LogicManager -> ExportCommand : execute(model)
activate ExportCommand

ExportCommand -> Model : getFocusedClass()
activate Model

Model --> ExportCommand : focusedClass
deactivate Model

ExportCommand -> Model : getStudentList()
activate Model

Model --> ExportCommand : students
deactivate Model

create ExportCsvStorageAction
ExportCommand -> ExportCsvStorageAction
activate ExportCsvStorageAction

ExportCsvStorageAction --> ExportCommand
deactivate ExportCsvStorageAction

create CommandResult
ExportCommand -> CommandResult
activate CommandResult

CommandResult --> ExportCommand : result
deactivate CommandResult

ExportCommand --> LogicManager : result
deactivate ExportCommand

LogicManager -> CommandResult : hasStorageAction()
activate CommandResult

CommandResult --> LogicManager : true
deactivate CommandResult

LogicManager -> CommandResult: getStorageAction()
activate CommandResult
CommandResult --> LogicManager : action
deactivate CommandResult

LogicManager -> ExportCsvStorageAction : act(storage)
activate ExportCsvStorageAction

ExportCsvStorageAction -> Storage : exportAsCsv(fileName, fileData)
activate Storage

Storage --> ExportCsvStorageAction
deactivate Storage

create CommandResult2
ExportCsvStorageAction -> CommandResult2
activate CommandResult2

CommandResult2 --> ExportCsvStorageAction
deactivate CommandResult2

ExportCsvStorageAction --> LogicManager : finalResult
deactivate ExportCsvStorageAction

[<--LogicManager
deactivate LogicManager
@enduml
