@startuml
!include style.puml

!define CLIPBOARD_COLOR #964B00


Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Clipboard" as clipboard CLIPBOARD_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR

user -[USER_COLOR]> ui : "extract emails"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("extract emails")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : getFilteredStudentList()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model


logic -[LOGIC_COLOR]> logic : generateUrl(students)
activate logic LOGIC_COLOR
deactivate logic

logic -[LOGIC_COLOR]> clipboard : setContent(url)
activate clipboard CLIPBOARD_COLOR

clipboard --[CLIPBOARD_COLOR]> logic
deactivate clipboard

logic --[LOGIC_COLOR]> ui : result
deactivate logic

ui--[UI_COLOR]> user : instructions
deactivate ui

@enduml
