@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterTasksCommandParser" as FilterTasksCommandParser LOGIC_COLOR
participant "predicate:FilterPredicate" as FilterPredicate LOGIC_COLOR
participant "f:FilterTasksCommand" as FilterTasksCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("t filter m/CS2103T c/y l/n")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("t filter m/CS2103T c/y l/n")
activate AddressBookParser

create FilterTasksCommandParser
AddressBookParser -> FilterTasksCommandParser
activate FilterTasksCommandParser

FilterTasksCommandParser --> AddressBookParser
deactivate FilterTasksCommandParser

AddressBookParser -> FilterTasksCommandParser : parse("m/CS2103T c/y l/n")
activate FilterTasksCommandParser

create FilterPredicate
FilterTasksCommandParser -> FilterPredicate
activate FilterPredicate

FilterPredicate --> FilterTasksCommandParser
deactivate FilterPredicate

create FilterTasksCommand
FilterTasksCommandParser -> FilterTasksCommand
activate FilterTasksCommand

FilterTasksCommand --> FilterTasksCommandParser : f
deactivate FilterTasksCommand

FilterTasksCommandParser --> AddressBookParser : f
deactivate FilterTasksCommandParser

FilterTasksCommandParser [hidden]--> AddressBookParser
destroy FilterTasksCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FilterTasksCommand : execute()
activate FilterTasksCommand

FilterTasksCommand -> Model : updateFilteredTaskList(predicate)
activate Model

Model --> FilterTasksCommand
deactivate Model

create CommandResult
FilterTasksCommand -> CommandResult : CommandResult(MESSAGE_SUCCESS)
activate CommandResult

CommandResult --> FilterTasksCommand
deactivate CommandResult

FilterTasksCommand --> LogicManager : result
deactivate FilterTasksCommand

FilterTasksCommand -[hidden]-> LogicManager
destroy FilterTasksCommand

[<--LogicManager
deactivate LogicManager
@enduml
