@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "a:FilterPropertyCommand" as FilterPropertyCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

LogicManager -> FilterPropertyCommand : execute(model)
activate FilterPropertyCommand

FilterPropertyCommand -> Model : updateFilteredPropertyList(...)
activate Model

Model -> FilterPropertyCommand
deactivate Model

create CommandResult
FilterPropertyCommand -> CommandResult
activate CommandResult

CommandResult --> FilterPropertyCommand
deactivate CommandResult

FilterPropertyCommand --> LogicManager : result
deactivate FilterPropertyCommand

[<--LogicManager
deactivate LogicManager

@enduml
