@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Command is valid])
    :Filter address book;
    :Display filtered address book;
else ([else])
    :Display error;
endif
stop
@enduml
