@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant ":FindCommand" as FindCommand LOGIC_COLOR
participant "predicate:NameContainsKeywordsPredicate" as NameContainsKeywordsPredicate LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(find David)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(find)
activate AddressBookParser

create FindCommandParser
AddressBookParser -> FindCommandParser
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

create NameContainsKeywordsPredicate
FindCommand -> NameContainsKeywordsPredicate
activate NameContainsKeywordsPredicate

NameContainsKeywordsPredicate --> FindCommand
deactivate NameContainsKeywordsPredicate

FindCommand --> FindCommandParser
deactivate FindCommand

FindCommandParser --> AddressBookParser
deactivate FindCommandParser
FindCommandParser -[hidden]-> AddressBookParser
destroy FindCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> FindCommand :execute(model)
activate FindCommand

FindCommand -> Model :updateFilteredPersonList(predicate)
activate Model

Model --> FindCommand
deactivate Model

FindCommand --> LogicManager
deactivate FindCommand
FindCommand -[hidden]-> LogicManager
destroy FindCommand

<-- LogicManager
deactivate LogicManager

@enduml