@startuml
'https://plantuml.com/activity-diagram-beta

start
:User types in command to find tasks by name;
repeat
  :Check format of input;
backward:Show correct format for entering command and user types again;
repeat while () is (invalid format)
-> valid format;
  :CodeConnect finds tasks in the TaskList according to the given string;
  stop
@enduml
