@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "<<interface>>\nPredicate" as Predicate

CombinedPersonPredicate .up.> Predicate
CombinedAppointmentPredicate .up.> Predicate

FindCommand -left-> "1" CombinedPersonPredicate
FindCommand -right-> "1" CombinedAppointmentPredicate

CombinedPersonPredicate --> "0..1" Name
CombinedPersonPredicate --> "0..1" Phone
CombinedPersonPredicate --> "0..1" Email
CombinedPersonPredicate --> "0..1" Address
CombinedPersonPredicate --> "*" Tag

CombinedAppointmentPredicate --> "0..1" reason
CombinedAppointmentPredicate --> "0..1" startDateTime
CombinedAppointmentPredicate --> "0..1" endDateTime
@enduml