@startuml
start
:User executes findn command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command is in an invalid format])
    :Show invalid command
    error message;

else ([else])
    :Show number of matching
    internships and filtered
    internship application list;
endif
stop
@enduml
