@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TrackOParser" as TrackOParser LOGIC_COLOR
participant "parser:FindItemCommandParser" as FindItemCommandParser LOGIC_COLOR
participant "predicate:ItemContainsKeywordsPredicate" as ItemContainsKeywordsPredicate LOGIC_COLOR
participant "command:FindItemCommand" as FindItemCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR

end box

[-> LogicManager : execute("findi chair mattress")
activate LogicManager

LogicManager -> TrackOParser : parseCommand("findi chair mattress")
activate TrackOParser

create FindItemCommandParser
TrackOParser -> FindItemCommandParser
activate FindItemCommandParser

FindItemCommandParser --> TrackOParser : parser
deactivate FindItemCommandParser

TrackOParser -> FindItemCommandParser : parse("chair mattress")
activate FindItemCommandParser

create ItemContainsKeywordsPredicate
FindItemCommandParser -> ItemContainsKeywordsPredicate: ItemContainsKeywordsPredicate(["chair", "mattress"])
activate ItemContainsKeywordsPredicate

ItemContainsKeywordsPredicate --> FindItemCommandParser : predicate
deactivate ItemContainsKeywordsPredicate

create FindItemCommand
FindItemCommandParser -> FindItemCommand : FindItemCommand(predicate)
activate FindItemCommand

FindItemCommand --> FindItemCommandParser : command
deactivate FindItemCommand

FindItemCommandParser --> TrackOParser : command
deactivate FindItemCommandParser


TrackOParser --> LogicManager : command
deactivate TrackOParser

destroy FindItemCommandParser

LogicManager -> FindItemCommand : execute(model)
activate FindItemCommand

FindItemCommand -> Model : updateFilteredItemList(predicate);
activate Model
deactivate Model

create CommandResult
FindItemCommand -> CommandResult
activate CommandResult

CommandResult --> FindItemCommand : result
deactivate CommandResult

FindItemCommand --> LogicManager : result
deactivate FindItemCommand

[<--LogicManager

destroy FindItemCommand
deactivate LogicManager
@enduml
