@startuml
skinparam activity {
    ArrowColor #A80036
    BackgroundColor #FEFECE
    BorderColor #A80036
    BorderThickness 1.5
}
start
:User executes find command with search terms;
:Find guest(s) whose fields match any search term;
:Set the guest(s) to the model;
stop

@enduml