@startuml
start
:User executes find person command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([at least 1 valid field prefix is given])
    :Construct a predicate based on
    the given keywords;
    :Filter the person list using
    the constructed predicate;
    :Display success message;
else ([else])
    :Display an invalid command format error;
endif
stop
@enduml
