@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HealthContactParser" as HealthContactParser LOGIC_COLOR
participant "f:FindAppointmentCommand" as FindBillCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":FilteredList<Appointment>" as FilteredList MODEL_COLOR
end box
[-> LogicManager : execute(fa n/John)
activate LogicManager

LogicManager -> HealthContactParser : parseCommand(fa n/John)
activate HealthContactParser

create FindBillCommand
HealthContactParser -> FindBillCommand
activate FindBillCommand

FindBillCommand --> HealthContactParser
deactivate FindBillCommand

HealthContactParser --> LogicManager : f
deactivate HealthContactParser

LogicManager -> FindBillCommand : execute()
activate FindBillCommand

FindBillCommand -> Model : updateFilteredAppointmentList(predicate)
activate Model

Model -> FilteredList: setPredicate(predicate)
activate FilteredList

FilteredList --> Model
deactivate FilteredList

Model --> FindBillCommand
deactivate Model

FindBillCommand --> LogicManager : result
deactivate FindBillCommand
FindBillCommand -[hidden]-> LogicManager : result
destroy FindBillCommand

[<--LogicManager
deactivate LogicManager
@enduml
