@startuml
start
:User enters FindTask command;
:HackAssist searches through \n the tasklist to find all tasks with \n matching keywords in their \n names and/or descriptions;
:HackAssist updates tasklist \n to display the search result;

stop
@enduml
