@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaAssistParser" as TaAssistParser LOGIC_COLOR
participant ":ClassCommandParser" as ClassCommandParser LOGIC_COLOR
participant "m:ModuleClass" as ModuleClass LOGIC_COLOR
participant "c:ClassCommand" as ClassCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("class CS1101S")
activate LogicManager

LogicManager -> TaAssistParser : parseCommand("class CS1101S")
activate TaAssistParser

create ClassCommandParser
TaAssistParser -> ClassCommandParser
activate ClassCommandParser

ClassCommandParser --> TaAssistParser
deactivate ClassCommandParser

TaAssistParser -> ClassCommandParser: parse("CS1101S")
activate ClassCommandParser


create ModuleClass
ClassCommandParser -> ModuleClass
activate ModuleClass

ModuleClass --> ClassCommandParser: m
deactivate ModuleClass


create ClassCommand
ClassCommandParser -> ClassCommand: m
activate ClassCommand

ClassCommand --> ClassCommandParser: c
deactivate ClassCommand

ClassCommandParser --> TaAssistParser: c
deactivate ClassCommandParser
ClassCommandParser -[hidden]-> TaAssistParser
destroy ClassCommandParser

TaAssistParser --> LogicManager: c
deactivate TaAssistParser

LogicManager -> ClassCommand: execute()
activate ClassCommand

ClassCommand -> Model: hasModuleClass(m)
activate Model
Model --> ClassCommand
deactivate Model

ClassCommand -> Model: enterFocusMode(m)
activate Model
Model --> ClassCommand
deactivate Model

create CommandResult
ClassCommand -> CommandResult
activate CommandResult

CommandResult --> ClassCommand
deactivate CommandResult

ClassCommand --> LogicManager: result
deactivate ClassCommand

LogicManager -->[
deactivate LogicManager

@enduml
