@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GetCommandParser" as GetCommandParser LOGIC_COLOR
participant "appton:GetAppointmentByDateCommand" as GetAppointmentByDateCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("get /appton")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("get /appton")
activate AddressBookParser

create GetCommandParser
AddressBookParser -> GetCommandParser
activate GetCommandParser

GetCommandParser --> AddressBookParser
deactivate GetCommandParser

AddressBookParser -> GetCommandParser : parse("/appton")
activate GetCommandParser

create GetAppointmentByDateCommand
GetCommandParser -> GetAppointmentByDateCommand
activate GetAppointmentByDateCommand

GetAppointmentByDateCommand --> GetCommandParser
deactivate GetAppointmentByDateCommand

GetCommandParser --> AddressBookParser
deactivate GetCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetCommandParser -[hidden]-> AddressBookParser
destroy GetCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> GetAppointmentByDateCommand : execute()
activate GetAppointmentByDateCommand

GetAppointmentByDateCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> GetAppointmentByDateCommand
deactivate Model

create CommandResult
GetAppointmentByDateCommand -> CommandResult
activate CommandResult

CommandResult --> GetAppointmentByDateCommand
deactivate CommandResult

GetAppointmentByDateCommand --> LogicManager : result
deactivate GetAppointmentByDateCommand

[<--LogicManager
deactivate LogicManager
@enduml