@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GetCommandParser" as GetCommandParser LOGIC_COLOR
participant ":GetHospitalWingParser" as GetHospitalWingParser LOGIC_COLOR
participant ":GetHospitalWingCommand" as GetHospitalWingCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("get /hw North")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("get /hw North")
activate AddressBookParser

create GetCommandParser
AddressBookParser -> GetCommandParser
activate GetCommandParser

GetCommandParser --> AddressBookParser
deactivate GetCommandParser

AddressBookParser -> GetCommandParser : parse("/hw North")
activate GetCommandParser

create GetHospitalWingParser
GetCommandParser -> GetHospitalWingParser
activate GetHospitalWingParser

GetHospitalWingParser --> GetCommandParser
deactivate GetHospitalWingParser

GetCommandParser -> GetHospitalWingParser : parse("North")
activate GetHospitalWingParser

create GetHospitalWingCommand
GetHospitalWingParser -> GetHospitalWingCommand
activate GetHospitalWingCommand

GetHospitalWingCommand --> GetHospitalWingParser
deactivate GetHospitalWingCommand

GetHospitalWingParser --> GetCommandParser
deactivate GetHospitalWingParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetHospitalWingParser -[hidden]-> GetCommandParser
destroy GetHospitalWingParser

GetCommandParser --> AddressBookParser
deactivate GetCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetCommandParser -[hidden]-> AddressBookParser
destroy GetCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> GetHospitalWingCommand : execute()
activate GetHospitalWingCommand

GetHospitalWingCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> GetHospitalWingCommand
deactivate Model

create CommandResult
GetHospitalWingCommand -> CommandResult
activate CommandResult

CommandResult --> GetHospitalWingCommand
deactivate CommandResult

GetHospitalWingCommand --> LogicManager : result
deactivate GetHospitalWingCommand

[<--LogicManager
deactivate LogicManager
@enduml
