@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GetCommandParser" as GetCommandParser LOGIC_COLOR
participant ":GetInpatientCommand" as GetInpatientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("get /inp")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("get /inp")
activate AddressBookParser

create GetCommandParser
AddressBookParser -> GetCommandParser
activate GetCommandParser

GetCommandParser --> AddressBookParser
deactivate GetCommandParser

AddressBookParser -> GetCommandParser : parse("/inp")
activate GetCommandParser

create GetInpatientCommand
GetCommandParser -> GetInpatientCommand
activate GetInpatientCommand

GetInpatientCommand --> GetCommandParser : instance of GetInpatientCommand
deactivate GetInpatientCommand

GetCommandParser --> AddressBookParser : instance of GetInpatientCommand
deactivate GetCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetCommandParser -[hidden]-> AddressBookParser
destroy GetCommandParser

AddressBookParser --> LogicManager : instance of GetInpatientCommand
deactivate AddressBookParser

LogicManager -> GetInpatientCommand : execute()
activate GetInpatientCommand

GetInpatientCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> GetInpatientCommand
deactivate Model

create CommandResult
GetInpatientCommand -> CommandResult
activate CommandResult

CommandResult --> GetInpatientCommand
deactivate CommandResult

GetInpatientCommand --> LogicManager : result
deactivate GetInpatientCommand

[<--LogicManager
deactivate LogicManager
@enduml
