@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GetCommandParser" as GetCommandParser LOGIC_COLOR
participant "nok:GetNextOfKinCommand" as GetNextOfKinCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("get /nok")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("get /nok")
activate AddressBookParser

create GetCommandParser
AddressBookParser -> GetCommandParser
activate GetCommandParser

GetCommandParser --> AddressBookParser
deactivate GetCommandParser

AddressBookParser -> GetCommandParser : parse("/nok")
activate GetCommandParser

create GetNextOfKinCommand
GetCommandParser -> GetNextOfKinCommand
activate GetNextOfKinCommand

GetNextOfKinCommand --> GetCommandParser
deactivate GetNextOfKinCommand

GetCommandParser --> AddressBookParser
deactivate GetCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetCommandParser -[hidden]-> AddressBookParser
destroy GetCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> GetNextOfKinCommand : execute()
activate GetNextOfKinCommand

GetNextOfKinCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> GetNextOfKinCommand
deactivate Model

create CommandResult
GetNextOfKinCommand -> CommandResult
activate CommandResult

CommandResult --> GetNextOfKinCommand
deactivate CommandResult

GetNextOfKinCommand --> LogicManager : result
deactivate GetNextOfKinCommand

[<--LogicManager
deactivate LogicManager
@enduml