@startuml
!include style.puml
'https://plantuml.com/sequence-diagram

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskListParser" as TaskListParser LOGIC_COLOR
participant ":ArchiveCommandParser" as ArchiveCommandParser LOGIC_COLOR
participant "f:ArchiveCommand" as ArchiveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("archive 1")
activate LogicManager

LogicManager -> TaskListParser : parseCommand("archive 1")
activate TaskListParser

create ArchiveCommandParser
TaskListParser -> ArchiveCommandParser
activate ArchiveCommandParser

ArchiveCommandParser --> TaskListParser
deactivate ArchiveCommandParser

ArchiveCommandParser -> ArchiveCommandParser : parse("1")
activate ArchiveCommandParser

create ArchiveCommand
ArchiveCommandParser -> ArchiveCommand
activate ArchiveCommand

ArchiveCommand --> ArchiveCommandParser : d
deactivate ArchiveCommand

ArchiveCommandParser --> TaskListParser : d
deactivate ArchiveCommandParser

ArchiveCommandParser -[hidden]-> TaskListParser
destroy ArchiveCommandParser

TaskListParser --> LogicManager : d
deactivate TaskListParser

LogicManager -> ArchiveCommand : execute()
activate ArchiveCommand

ArchiveCommand -> Model : archive(1)
activate Model

Model --> ArchiveCommand
deactivate Model

create CommandResult
ArchiveCommand -> CommandResult
activate CommandResult

CommandResult --> ArchiveCommand
deactivate CommandResult

ArchiveCommand --> LogicManager : result
deactivate ArchiveCommand

[<--LogicManager
deactivate LogicManager
@enduml
