@startuml
start
:User enters Import command;

if () then ([Is invalid parameter])
    :TrackAScholar displays \nerror message indicating \ninvalid user input;

else ([Is valid parameters])

    if () then ([trackAScholarImport.json\ndata file exist])

        if () then ([trackAScholarImport.json\nis in valid format])
            :Read data file to obtain\nimported applicant list;

            if () then ([import with replacement])
                :Add all imported applicants \ninto current applicant list and\napplicants with the same\nname are replaced by the\nimported applicants;

            else ([import without replacement])
                :Add all imported applicants \ninto current applicant list and\napplicants with the same\nname are not replaced;
            endif

            :TrackAScholar updates\nto display new list;

        else ([else])
            :TrackAScholar displays \nerror message indicating \nfile format is wrong;
        endif

    else ([else])
        :TrackAScholar displays \nerror message indicating \nfile does not exist;

    endif

endif
stop
@enduml
