@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ImportCommandParser" as ImportCommandParser LOGIC_COLOR
participant ":ImportCommand" as ImportCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":JsonAddressBookStorage" as JsonAddressBookStorage STORAGE_COLOR
end box

[-> LogicManager : execute("import nus/json")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("import nus/json")
activate AddressBookParser

create ImportCommandParser
AddressBookParser -> ImportCommandParser
activate ImportCommandParser

ImportCommandParser --> AddressBookParser
deactivate ImportCommandParser

AddressBookParser -> ImportCommandParser : parse("nus.json")
activate ImportCommandParser

create ImportCommand
ImportCommandParser -> ImportCommand
activate ImportCommand

ImportCommand --> ImportCommandParser
deactivate ImportCommand

ImportCommandParser --> AddressBookParser
deactivate ImportCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ImportCommandParser -[hidden]-> AddressBookParser
destroy ImportCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> ImportCommand : execute()
activate ImportCommand

create JsonAddressBookStorage
ImportCommand -> JsonAddressBookStorage
activate JsonAddressBookStorage

JsonAddressBookStorage --> ImportCommand
deactivate JsonAddressBookStorage

ImportCommand -> JsonAddressBookStorage: readAddressBook()
activate JsonAddressBookStorage

JsonAddressBookStorage --> ImportCommand
deactivate JsonAddressBookStorage

ImportCommand -> Model : appendAddressBook(toAppend)
activate Model

Model --> ImportCommand
deactivate Model

create CommandResult
ImportCommand -> CommandResult
activate CommandResult

CommandResult --> ImportCommand
deactivate CommandResult

ImportCommand --> LogicManager : result
deactivate ImportCommand

[<--LogicManager
deactivate LogicManager
@enduml