@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

UniqueTagList -> "0...100" Tag
UniqueItemList -> "0...10000" Item
note right : 10,000 items enforced by UniqueItemList

Item *-up-> "0...100" Tag
note right : 100 tags enforced by UniqueTagList

Item *--> "1" ItemUnit
Item *--> "1" ItemBoughtDate
Item *--> "1" ItemExpiryDate
Item *--> "1" ItemQuantity
Item *--> "1" ItemName
Item *--> "1" ItemPrice
Item *--> "1" ItemRemark
Tag *-right--> "1" TagName
@enduml
