@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "JeeqTracker Storage" #F4F6F6{
Class "<<interface>>\nJeeqTrackerStorage" as JeeqTrackerStorage
Class JsonJeeqTrackerStorage
Class JsonSerializableJeeqTracker
Class JsonAdaptedClient
Class JsonAdaptedTag
Class JsonAdaptedCompany
Class JsonAdaptedTransaction
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" JeeqTrackerStorage

Storage -right-|> JeeqTrackerStorage

JsonJeeqTrackerStorage .up.|> JeeqTrackerStorage
JsonJeeqTrackerStorage ..> JsonSerializableJeeqTracker
JsonSerializableJeeqTracker --> "*" JsonAdaptedClient
JsonAdaptedClient --> "*" JsonAdaptedTag
JsonAdaptedClient --> "*" JsonAdaptedCompany
JsonAdaptedClient --> "*" JsonAdaptedTransaction

@enduml
