@startuml
!include style.puml
skinparam classBackgroundColor LOGIC_COLOR

abstract class Lesson
Class Lab
Class Lecture
Class Recitation
Class Tutorial
Lesson <|-- Lab
Lesson <|-- Lecture
Lesson <|-- Recitation
Lesson <|-- Tutorial

@enduml
