@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ListStudentCommand" as ListStudentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

-> MainWindow : executeCommand(commandText)
activate MainWindow

MainWindow -> LogicManager : execute(commandText)
activate LogicManager
LogicManager -> ListStudentCommand : execute(model)
activate ListStudentCommand

ListStudentCommand -> Model : updateFilteredStudentList(PREDICATE_SHOW_ALL_STUDENTS)
activate Model

Model --> ListStudentCommand :
deactivate Model

create CommandResult
ListStudentCommand -> CommandResult
activate CommandResult

CommandResult --> ListStudentCommand
deactivate CommandResult

ListStudentCommand --> LogicManager : commandResult
deactivate ListStudentCommand

LogicManager --> MainWindow : commandResult
deactivate LogicManager

MainWindow -> MainWindow : handleList(commandResult)
activate MainWindow

[<-- MainWindow
deactivate MainWindow
@enduml
