@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "ListEventsCommandParser" as ListEventsCommandParser LOGIC_COLOR
participant "l:ListEventsCommand" as ListEventsCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant "filteredEvents:FilteredList" as eventList MODEL_COLOR
end box

[-> LogicManager : execute(cmd)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(cmd)
activate AddressBookParser

create ListEventsCommandParser
AddressBookParser -> ListEventsCommandParser :
activate ListEventsCommandParser

create ListEventsCommand
ListEventsCommandParser -> ListEventsCommand :parse(cmd)
activate ListEventsCommand

ListEventsCommand --> ListEventsCommandParser : l
deactivate ListEventsCommand

ListEventsCommandParser --> AddressBookParser : l
deactivate ListEventsCommandParser

AddressBookParser --> LogicManager : l
deactivate AddressBookParser
AddressBookParser -[hidden]-> LogicManager
destroy AddressBookParser

LogicManager -> ListEventsCommand : execute()
activate ListEventsCommand

ListEventsCommand -> ModelManager : updateFilteredEventList\n(PREDICATE_SHOW\n_ALL_EVENTS)
activate ModelManager

ModelManager -> eventList : setPredicate\n(PREDICATE_SHOW\n_ALL_EVENTS)
activate eventList

eventList --> ModelManager :
deactivate eventList

ModelManager --> ListEventsCommand :
deactivate ModelManager

ListEventsCommand --> LogicManager : result
deactivate ListEventsCommand
ListEventsCommand -[hidden]-> LogicManager : result
destroy ListEventsCommand

[<--LogicManager
deactivate LogicManager
@enduml
