@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MyInsuRecParser" as MyInsuRecParser LOGIC_COLOR
participant "l:ListMeetingCommand" as ListMeetingCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("listMeeting d/tomorrow")
activate LogicManager

LogicManager -> MyInsuRecParser : parseCommand("listMeeting d/tomorrow")
activate MyInsuRecParser

create ListMeetingCommand
MyInsuRecParser -> ListMeetingCommand
activate ListMeetingCommand

ListMeetingCommand --> MyInsuRecParser : l
deactivate ListMeetingCommand

MyInsuRecParser --> LogicManager : l
deactivate MyInsuRecParser

LogicManager -> ListMeetingCommand : execute()
activate ListMeetingCommand

ListMeetingCommand -> Model : updateFilteredMeetingList(predicate)
activate Model

Model --> ListMeetingCommand
deactivate Model

create CommandResult
ListMeetingCommand -> CommandResult
activate CommandResult

CommandResult --> ListMeetingCommand
deactivate CommandResult

ListMeetingCommand --> LogicManager : result
deactivate ListMeetingCommand

[<--LogicManager
deactivate LogicManager
@enduml
