@startuml
!include style.puml
'https://plantuml.com/sequence-diagram

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "d:ListCommand" as ListCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box


LogicManager -> ListCommand : execute()
activate ListCommand

ListCommand -> Model : updateFilteredTaskList(predicate)
activate Model

Model --> ListCommand
deactivate Model

ListCommand -> Model : updateFilterStatus("Unmarked Tasks")
activate Model

Model --> ListCommand
deactivate Model

ListCommand -> Model : updateFilterStatus("Modules containing "CS2103T")
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand : result
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand

[<--LogicManager
deactivate LogicManager
@enduml
