@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PrimaryParser" as PrimaryParser LOGIC_COLOR
participant ":LoanCommandParser" as LoanCommandParser LOGIC_COLOR
participant "l:LoanCommand" as LoanCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("loan 2 2")
activate LogicManager

LogicManager -> PrimaryParser : parse("loan 2 2")
activate PrimaryParser

create LoanCommandParser
PrimaryParser -> LoanCommandParser
activate LoanCommandParser

LoanCommandParser --> PrimaryParser
deactivate LoanCommandParser

PrimaryParser -> LoanCommandParser : parse("2 2")
activate LoanCommandParser

create LoanCommand
LoanCommandParser -> LoanCommand
activate LoanCommand

LoanCommand --> LoanCommandParser : l
deactivate LoanCommand

LoanCommandParser --> PrimaryParser : l
deactivate LoanCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
LoanCommandParser -[hidden]-> PrimaryParser
destroy LoanCommandParser

PrimaryParser --> LogicManager : l
deactivate PrimaryParser

LogicManager -> LoanCommand : execute()
activate LoanCommand

LoanCommand -> Model : loan(2, 2)
activate Model

Model --> LoanCommand
deactivate Model

create CommandResult
LoanCommand -> CommandResult
activate CommandResult

CommandResult --> LoanCommand
deactivate CommandResult

LoanCommand --> LogicManager : result
deactivate LoanCommand

[<--LogicManager
deactivate LogicManager
@enduml
