@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor BLACK
skinparam classBackgroundColor LOGIC_COLOR

package Logic {
Class XYZCommand
Class CommandResult
Class "<<interface>>\nCommand" as Command

Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

package Storage {
Class HiddenStorage #FFFFFF
}

Class "<<interface>>\nCommand" as Command
Class XYZCommand


package "Parser classes"{
Class "<<interface>>\nCommandParser" as CommandParser
Class Rc4hdbParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
LogicManager .> Command
LogicManager .down.> CommandResult
LogicManager -> Model
LogicManager --> Storage
LogicManager --> Rc4hdbParser

Rc4hdbParser .down.> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
Rc4hdbParser ..> Command : returns >
XYZCommandParser .up.|> CommandParser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand .up.|> Command

@enduml
