@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MailEventCommandParser" as MailEventCommandParser LOGIC_COLOR
participant "c:MailEventnCommand" as MailEventCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":UniqueEventList" as UniqueEventList MODEL_COLOR
end box

[-> LogicManager : execute(cmd)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(cmd)
activate AddressBookParser

create MailEventCommandParser
AddressBookParser -> MailEventCommandParser
activate MailEventCommandParser

create MailEventCommand
MailEventCommandParser -> MailEventCommand : parse(cmd)
activate MailEventCommand

MailEventCommand --> MailEventCommandParser
deactivate MailEventCommand

MailEventCommandParser --> AddressBookParser
deactivate MailEventCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser
destroy MailEventCommandParser

LogicManager -> MailEventCommand : execute()
activate MailEventCommand

MailEventCommand -> ModelManager : getFilteredEventList()
activate ModelManager

ModelManager -> AddressBook : getEventList()
activate AddressBook

AddressBook --> ModelManager : EventList
deactivate AddressBook


ModelManager --> MailEventCommand : EventList
deactivate ModelManager

MailEventCommand --> UniqueEventList : get(eventIndex)
activate UniqueEventList

UniqueEventList --> MailEventCommand : event
deactivate UniqueEventList

MailEventCommand -> MailEventCommand : getMailingList()

MailEventCommand --> LogicManager : result
deactivate MailEventCommand
MailEventCommand -[hidden]-> LogicManager : result
destroy MailEventCommand

[<--LogicManager
deactivate LogicManager
@enduml
