@startuml
!include style.puml

start
:User add task;
repeat
:User input\n mark command ;
backward:User input unmark\n command for task ;
repeat while (new workload\n for task?) is (yes)
->no;
stop
@enduml