@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam linetype ortho
hide empty methods
show members
hide empty members

title Final state after parsing the <plain><font:monospaced><back:lightgray>mark</back></font></plain> example

class MarkCommand as "__:MarkCommand__"
together {
class DebtorIndex1 as "__1:Index__"
class DebtIndex2 as "__2:Index__"
class DebtIndex3 as "__3:Index__"
}

Package Model {
class OldPerson as "__person1:Person__"
    class DebtList as "__initialList:DebtList__"
    object "__1:Debt__" as Debt1
    object "__2:Debt__" as Debt2
    object "__3:Debt__" as Debt3
}

Debt1 : isPaid = false
Debt2 : isPaid = false
Debt3 : isPaid = false

MarkCommand -up-> "debtor index" DebtorIndex1
MarkCommand -down---> "debt index" DebtIndex2
MarkCommand --> "debt index" DebtIndex3
DebtorIndex1 -d[hidden]-> DebtIndex2
DebtIndex2 -d[hidden]-> DebtIndex3

OldPerson --> DebtList
DebtList --> Debt1
DebtList --> Debt2
DebtList --> Debt3

@end
