@startuml
'https://plantuml.com/sequence-diagram
!include style.puml

Participant ":MatchBuyerCommand" as matchCommand LOGIC_COLOR
Participant ":ArrayList<Predicate>" as arrayList USER_COLOR
Participant ":FilterPropsByPricePredicate" as pricePred MODEL_COLOR_T1
Participant ":FilterPropsContainingAnyCharacteristicPredicate" as charPred MODEL_COLOR_T1
Participant ":FilterPropertiesCommand" as filterProps LOGIC_COLOR


[-[LOGIC_COLOR]> matchCommand: execute(model)
activate matchCommand LOGIC_COLOR

create arrayList
matchCommand -[LOGIC_COLOR]> arrayList
activate arrayList USER_COLOR
arrayList --[USER_COLOR]> matchCommand
deactivate arrayList

create pricePred
matchCommand -[LOGIC_COLOR]> pricePred: Buyer's PriceRange
activate pricePred MODEL_COLOR_T1
pricePred --[MODEL_COLOR_T1]> matchCommand
deactivate pricePred

matchCommand -[LOGIC_COLOR]> arrayList: add(filterPropsByPricePredicate)
activate arrayList USER_COLOR
arrayList --[USER_COLOR]> matchCommand
deactivate arrayList

create charPred
matchCommand -[LOGIC_COLOR]> charPred: Buyer's Characteristics
activate charPred MODEL_COLOR_T1
charPred --[MODEL_COLOR_T1]> matchCommand
deactivate charPred

matchCommand -[LOGIC_COLOR]> arrayList: add(filterPropsContainingAnyCharacteristicPredicate)
activate arrayList USER_COLOR
arrayList --[USER_COLOR]> matchCommand
deactivate arrayList

matchCommand -[LOGIC_COLOR]> arrayList: stream().reduce(Predicate::and)
activate arrayList USER_COLOR
arrayList --[USER_COLOR]> matchCommand: combinedPredicate
deactivate arrayList

create filterProps
matchCommand -[LOGIC_COLOR]> filterProps: combinedPredicate
activate filterProps LOGIC_COLOR
filterProps --[LOGIC_COLOR]> matchCommand
deactivate filterProps

matchCommand -[LOGIC_COLOR]> filterProps: execute(model)
activate filterProps LOGIC_COLOR
filterProps --[LOGIC_COLOR]> matchCommand
deactivate filterProps

[<[LOGIC_COLOR]-- matchCommand: CommandResult
deactivate matchCommand

@enduml
