@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyFoodRem" as ReadOnlyFoodRem
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class FoodRem
Class ModelManager
Class UserPrefs

Class UniqueItemList
Class Item
Class Unit
Class BoughtDate
Class ExpiryDate
Class Name
Class Quantity
Class Price
Class Tag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FoodRem .up.|> ReadOnlyFoodRem

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyFoodRem
ModelManager -left-> "1" FoodRem
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FoodRem *--> "1" UniqueItemList
UniqueItemList --> "~* all" Item
Item *--> Name
Item *--> Quantity
Item *--> BoughtDate
Item *--> ExpiryDate
Item *--> Unit
Item *--> Price
Item *--> "*" Tag

Name -[hidden]right-> Quantity
Quantity -[hidden]right-> Unit
Unit -[hidden]right-> BoughtDate

ModelManager -->"~* filtered" Item
@enduml
