@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyWaddle" as ReadOnlyWaddle
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class Waddle
Class ModelManager
Class UserPrefs

Class UniqueItineraryList
Class Itinerary
Class People
Class Duration
Class Description
Class Country
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Waddle .up.|> ReadOnlyWaddle

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyWaddle
ModelManager -left-> "1" Waddle
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Waddle *--> "1" UniqueItineraryList
UniqueItineraryList --> "~* all" Itinerary
Itinerary *--> Description
Itinerary *--> Country
Itinerary *--> Duration
Itinerary *--> People

Description -[hidden]right-> Country
Country -[hidden]right-> People
People -[hidden]right-> Duration

ModelManager -->"~* filtered" Itinerary
@enduml
