@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

MyInsuRec *-right-> "1" UniqueClientList
MyInsuRec *-right-> "1" UniqueProductList
UniqueProductList -[hidden]down- UniqueClientList
UniqueProductList -[hidden]down- UniqueClientList

UniqueProductList *-right-> "*" Product
UniqueClientList -right-> Client

Client -up-> "*" Product

Client *--> Name
Client *--> Phone
Client *--> Email
Client *--> Address
@enduml
