@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Task <<Rectangle>>{
Class Task
Class TaskDeadline
Class TaskDescription
Class TaskMark

}

Class UniqueTaskList
Class ModelManager

UniqueTaskList --> "~* all" Task
Task *--> TaskDescription
Task *--> TaskDeadline
Task *--> TaskMark

TaskDescription -[hidden]right-> TaskDeadline

ModelManager -->"~* filtered" Task

@enduml
