@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyFriday" as ReadOnlyFriday
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class Friday
Class ModelManager
Class UserPrefs

Class UniqueStudentList
Class Student
Class MasteryCheck
Class TelegramHandle
Class Name
Class Consultation
Class Tag
Class Remark
Class GradesList

Class AliasMap
Class Alias
Class ReservedKeyword

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Friday .up.|> ReadOnlyFriday

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyFriday
ModelManager -left-> "1" Friday
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Friday *--> "1" UniqueStudentList
Friday *--> "1" AliasMap
UniqueStudentList --> "~* all" Student
AliasMap *--> Alias
AliasMap *--> ReservedKeyword
Alias <--> ReservedKeyword

Student *--> Name
Student *--> TelegramHandle
Student *--> MasteryCheck
Student *--> Consultation
Student *--> "*" Tag
Student *--> Remark
Student *--> GradesList

Alias -[hidden]right-> ReservedKeyword

ModelManager -->"~* filtered" Student
@enduml
