@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyMeetingList" as ReadOnlyMeetingList
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class MeetingList
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag

Class UniqueMeetingList
Class Meeting

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
MeetingList .up.|> ReadOnlyMeetingList

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .down.> ReadOnlyAddressBook
Model .left.> ReadOnlyMeetingList
ModelManager -down-> "1" AddressBook
ModelManager -left-> "1" MeetingList
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
MeetingList *--> "1" UniqueMeetingList
UniqueMeetingList --> "~* all" Meeting
UniquePersonList --> "~* all" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Person
ModelManager -->"~* filtered" Meeting
@enduml
