@startuml
!include style.puml

box UI UI_COLOR_T1
participant "commandTextField:TextField" as TextField UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":CommandHistoryManager" as CommandHistoryManager STORAGE_COLOR
end box

[-> TextField : key press("DOWN")
activate TextField

TextField -> MainWindow : getNextCommand()
activate MainWindow

MainWindow -> LogicManager : getNextCommand()
activate LogicManager

LogicManager -> StorageManager : getNextCommand()
activate StorageManager

StorageManager -> CommandHistoryManager : getNextCommand()
activate CommandHistoryManager

CommandHistoryManager --> StorageManager : command
deactivate CommandHistoryManager

StorageManager --> LogicManager : command
deactivate StorageManager

LogicManager --> MainWindow : command
deactivate LogicManager

MainWindow --> TextField : command
deactivate MainWindow

TextField -> TextField : setText(command)
TextField -> TextField : positionCaret(command.length())
[<-- TextField
deactivate TextField

@enduml
