@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Note *--> Title
Note *--> Content
Note "*" <--> "*" Tag
Person "1..*" <-up-> "*" Tag
@enduml
