@startuml
'https://plantuml.com/activity-diagram-beta
title Parsing of Mastery Check Command

start
:user executes "addmc" command;
:parse user input;

if () then ([all required prefix present])
    :check validity of lesson description;

    if () then ([valid description])
        :check validity of date time;

        if () then ([start date before end date])
          :check validity of student index;

          if () then ([valid integer])
            :create new Mastery Check Command;

          else ([else])
          endif

        else ([else])
            :throw ParseException;
        endif

    else ([else])
        :throw ParseException;
    endif

else ([else])
    :throw ParseException;
endif
stop
@enduml
