@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class "<<interface>>\nArgumentToken" as ArgumentToken
Class FlagTokenizer
Class Prefix
Class Flag
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
AddressBookParser ..> Command : returns >
XYZCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
XYZCommandParser ..> FlagTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
FlagTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
CliSyntax ..> Flag
ArgumentMultimap *-- ArgumentToken
XYZCommandParser ..> ParserUtil
ArgumentTokenizer .down.> Prefix
FlagTokenizer .down.> Flag
Flag .down.|> ArgumentToken
Prefix .down.|> ArgumentToken
XYZCommand -up-|> Command
@enduml
