@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

Class "<<interface>>\nCommandLine.ITypeConverter" as ITypeConverter #FFA500
Class TruthTableParser
Class ParserUtil
Class ArgumentTokenizer
Class CommandLine #FFA500

Class HiddenOutside #FFFFFF
HiddenOutside ..> TruthTableParser

TruthTableParser .down.> ArgumentTokenizer
TruthTableParser .down.> CommandLine
CommandLine .down.> ABCConverter

CommandLine ..> XYZCommand : creates >
TruthTableParser ..> Command : returns >
ABCConverter ..> ParserUtil
ABCConverter -up-|> ITypeConverter
XYZCommand -up-|> Command
@enduml
