@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Person "1..*" <--> "*" Tag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Birthday
Person *-right-> Loan
Person *--right-> "*" LoanHistory
LoanHistory --> "1" Loan
LoanHistory --> "1" Reason
@enduml
