@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
    Class AddressBook
    Class Model
    Class Person
    Class Task
    Class PersonTaskBridge
    Class PersonTaskBridgeList
}

Person --> "*" PersonTaskBridge
Task --> "*" PersonTaskBridge
PersonTaskBridgeList *-up-> "*" PersonTaskBridge

AddressBook *--> "1" PersonTaskBridgeList
Model --> "~* all" PersonTaskBridge

@enduml
