@startuml
!include style.puml
skinparam linetype polyline
skinparam linetype ortho
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
    Class AddressBook
    Class Task
    Class Person
    Class PersonTaskBridge
    Class PersonTaskBridgeList
    
    Task -d- Person : > assigned to
    (Person, Task) .. PersonTaskBridge
    PersonTaskBridgeList "*" *-up-> PersonTaskBridge
    AddressBook "1" *--> PersonTaskBridgeList
}
@enduml
