@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CondoneryParser" as CondoneryParser LOGIC_COLOR
participant ":RangePropertyCommandParser" as RangePropertyCommandParser LOGIC_COLOR
participant ":RangePropertyCommand" as RangePropertyCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":PropertyPriceWithinRangePredicate" as PropertyPriceWithinRangePredicate MODEL_COLOR
end box

[-> LogicManager : execute()
activate LogicManager

LogicManager -> CondoneryParser : parseCommand(...)
activate CondoneryParser

create RangePropertyCommandParser
CondoneryParser -> RangePropertyCommandParser
activate RangePropertyCommandParser

RangePropertyCommandParser --> CondoneryParser
deactivate RangePropertyCommandParser

CondoneryParser -> RangePropertyCommandParser : parse(args)
activate RangePropertyCommandParser

create PropertyPriceWithinRangePredicate
RangePropertyCommandParser -> PropertyPriceWithinRangePredicate
activate PropertyPriceWithinRangePredicate

PropertyPriceWithinRangePredicate --> RangePropertyCommandParser
deactivate PropertyPriceWithinRangePredicate

create RangePropertyCommand
RangePropertyCommandParser -> RangePropertyCommand
activate RangePropertyCommand

RangePropertyCommand --> RangePropertyCommandParser
deactivate RangePropertyCommand

RangePropertyCommandParser --> CondoneryParser
deactivate RangePropertyCommandParser

CondoneryParser --> LogicManager
deactivate CondoneryParser

LogicManager -> RangePropertyCommand : execute(...)
activate RangePropertyCommand

RangePropertyCommand -> Model : updateFilteredPropertyList(...)
activate Model

Model --> RangePropertyCommand
deactivate Model

RangePropertyCommand --> LogicManager
deactivate RangePropertyCommand

[<--LogicManager
deactivate LogicManager
@enduml