@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "a:RangePropertyCommand" as RangePropertyCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

LogicManager -> RangePropertyCommand : execute(model)
activate RangePropertyCommand

RangePropertyCommand -> Model : updateFilteredPropertyList(predicate)
activate Model

Model -> RangePropertyCommand
deactivate Model

create CommandResult
RangePropertyCommand -> CommandResult
activate CommandResult

CommandResult --> RangePropertyCommand
deactivate CommandResult

RangePropertyCommand --> LogicManager : result
deactivate RangePropertyCommand

[<--LogicManager
deactivate LogicManager

@enduml
