@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandHistory" as CommandHistory LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant "u:RedoCommand" as RedoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInternshipBook" as VersionedInternshipBook MODEL_COLOR
end box
[-> LogicManager : execute(redo)
activate LogicManager

LogicManager -> InternshipBookParser : parseCommand(redo)
activate InternshipBookParser

create RedoCommand
InternshipBookParser -> RedoCommand
activate RedoCommand

RedoCommand --> InternshipBookParser
deactivate RedoCommand

InternshipBookParser --> LogicManager : u
deactivate InternshipBookParser

LogicManager -> RedoCommand : execute()
activate RedoCommand

RedoCommand -> Model : redoInternshipBook()
activate Model

Model -> VersionedInternshipBook : redo()
activate VersionedInternshipBook

VersionedInternshipBook -> VersionedInternshipBook :resetData(ReadOnlyInternshipBook)
VersionedInternshipBook --> Model :
deactivate VersionedInternshipBook

Model --> RedoCommand
deactivate Model

RedoCommand -> CommandHistory : getNextModifyCommand()
activate CommandHistory

CommandHistory --> RedoCommand
deactivate CommandHistory

RedoCommand --> LogicManager : result

deactivate RedoCommand
RedoCommand -[hidden]-> LogicManager : result
destroy RedoCommand

[<--LogicManager
deactivate LogicManager
@enduml
