@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "r:RemindCommand" as RemindCommand LOGIC_COLOR
participant "c:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> MainWindow : fillInnerParts()
activate MainWindow

MainWindow -> LogicManager : execute()
activate LogicManager

LogicManager -> RemindCommand : execute()
activate RemindCommand

RemindCommand -> Model : updateFilteredApplicationsWithUpcomingInterviewList()
activate Model

Model --> RemindCommand
deactivate Model

create CommandResult
RemindCommand -> CommandResult :
activate CommandResult

CommandResult --> RemindCommand
deactivate CommandResult

RemindCommand --> LogicManager
deactivate RemindCommand


LogicManager --> MainWindow : c
deactivate LogicManager

MainWindow -> MainWindow : handleReminder()
activate MainWindow

MainWindow --> MainWindow
deactivate MainWindow

@enduml
