@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PrimaryParser" as PrimaryParser LOGIC_COLOR
participant ":ReturnCommandParser" as ReturnCommandParser LOGIC_COLOR
participant "r:ReturnCommand" as ReturnCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("return 2")
activate LogicManager

LogicManager -> PrimaryParser : parse("return 2")
activate PrimaryParser

create ReturnCommandParser
PrimaryParser -> ReturnCommandParser
activate ReturnCommandParser

ReturnCommandParser --> PrimaryParser
deactivate ReturnCommandParser

PrimaryParser -> ReturnCommandParser : parse("2")
activate ReturnCommandParser

create ReturnCommand
ReturnCommandParser -> ReturnCommand
activate ReturnCommand

ReturnCommand --> ReturnCommandParser : r
deactivate ReturnCommand

ReturnCommandParser --> PrimaryParser : r
deactivate ReturnCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ReturnCommandParser -[hidden]-> PrimaryParser
destroy ReturnCommandParser

PrimaryParser --> LogicManager : r
deactivate PrimaryParser

LogicManager -> ReturnCommand : execute()
activate ReturnCommand

ReturnCommand -> Model : returnLoanedBook(2)
activate Model

Model --> ReturnCommand
deactivate Model

create CommandResult
ReturnCommand -> CommandResult
activate CommandResult

CommandResult --> ReturnCommand
deactivate CommandResult

ReturnCommand --> LogicManager : result
deactivate ReturnCommand

[<--LogicManager
deactivate LogicManager
@enduml
