@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SoConnectParser" as SoConnectParser LOGIC_COLOR
participant ":SearchCommandParser" as SearchCommandParser LOGIC_COLOR
participant "s:SearchCommand" as SearchCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("search n/John a/NUS")
activate LogicManager

LogicManager -> SoConnectParser : parseCommand("search n/John a/NUS")
activate SoConnectParser

create SearchCommandParser
SoConnectParser -> SearchCommandParser
activate SearchCommandParser

SearchCommandParser --> SoConnectParser
deactivate SearchCommandParser

SoConnectParser -> SearchCommandParser : parse(" n/John a/NUS")
activate SearchCommandParser

create SearchCommand
SearchCommandParser -> SearchCommand
activate SearchCommand

SearchCommand --> SearchCommandParser : s
deactivate SearchCommand

SearchCommandParser --> SoConnectParser : s
deactivate SearchCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SearchCommandParser -[hidden]-> SoConnectParser
destroy SearchCommandParser

SoConnectParser --> LogicManager : s
deactivate SoConnectParser

LogicManager -> SearchCommand : execute()
activate SearchCommand

SearchCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> SearchCommand
deactivate Model

create CommandResult
SearchCommand -> CommandResult
activate CommandResult

CommandResult --> SearchCommand : result
deactivate CommandResult

SearchCommand --> LogicManager : result
deactivate SearchCommand

[<--LogicManager
deactivate LogicManager
@enduml
