@startuml
'https://plantuml.com/class-diagram
!include style.puml

package Pupilist <<Rectangle>> {

package Model  {
    Class SessionList #red
    Class Session #red
}

package Logic <<Rectangle>> {
    skinparam arrowColor LOGIC_COLOR
    skinparam classBackgroundColor LOGIC_COLOR
    Class EditPersonDescriptor
    Class SessionCommand
}

SessionCommand ----down-> "  1" Session:"    "
SessionList -right-> "0...*" Session
EditPersonDescriptor --down->"0...1" Session

}

@enduml
