@startuml
'https://plantuml.com/object-diagram

object "<u> Walter:Person" as Walter {
    position = "Professor"
    phone = "91234567"
}

object "<u> Jesse:Person" as Jesse {
    position = "Student"
    phone = "98765432"
}

map "<u> :AddressBook" as AddressBook {
    <u>:Person1 *-> Walter
    <u>:Person2 *--> Jesse
}

@enduml
