@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":IncludeCommandParser" as IncludeCommandParser LOGIC_COLOR
participant "i:addTelegram" as addTelegram LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("include 1 \TELEGRAM #t.me/JohnDoe123")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("include 1 \TELEGRAM #t.me/JohnDoe123")
activate AddressBookParser

create IncludeCommandParser
AddressBookParser -> IncludeCommandParser
activate IncludeCommandParser

IncludeCommandParser --> AddressBookParser
deactivate IncludeCommandParser

AddressBookParser -> IncludeCommandParser : parse("1 \TELEGRAM #t.me/JohnDoe123")
activate IncludeCommandParser

create addTelegram
IncludeCommandParser -> addTelegram
activate addTelegram

addTelegram --> IncludeCommandParser : i
deactivate addTelegram

IncludeCommandParser --> AddressBookParser : i
deactivate IncludeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
IncludeCommandParser -[hidden]-> AddressBookParser
destroy IncludeCommandParser

AddressBookParser --> LogicManager : i
deactivate AddressBookParser

LogicManager -> addTelegram : execute()
activate addTelegram

addTelegram -> Model : addTelegram(1, t.me/JohnDoe123)
activate Model

Model --> addTelegram
deactivate Model

create CommandResult
addTelegram -> CommandResult
activate CommandResult

CommandResult --> addTelegram
deactivate CommandResult

addTelegram --> LogicManager : result
deactivate addTelegram

[<--LogicManager
deactivate LogicManager
@enduml
