@startuml
skinparam defaultFontSize 20
!include style.puml


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":IncludeCommandParser" as IncludeCommandParser LOGIC_COLOR
participant "i:IncludeCommand" as IncludeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("include 1 s/TELEGRAM #/JohnDoe123")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("include 1 s/TELEGRAM #/JohnDoe123")
activate AddressBookParser

create IncludeCommandParser
AddressBookParser -> IncludeCommandParser
activate IncludeCommandParser

IncludeCommandParser --> AddressBookParser
deactivate IncludeCommandParser

AddressBookParser -> IncludeCommandParser : parse("1 s/TELEGRAM #/JohnDoe123")
activate IncludeCommandParser

create IncludeCommand
IncludeCommandParser -> IncludeCommand
activate IncludeCommand

IncludeCommand --> IncludeCommandParser : i
deactivate IncludeCommand

IncludeCommandParser --> AddressBookParser : i
deactivate IncludeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
IncludeCommandParser -[hidden]-> AddressBookParser
destroy IncludeCommandParser

AddressBookParser --> LogicManager : i
deactivate AddressBookParser

LogicManager -> IncludeCommand : execute()
activate IncludeCommand

IncludeCommand -> Model : IncludeCommand(1, TELEGRAM, JohnDoe123)
activate Model

Model --> IncludeCommand
deactivate Model

create CommandResult
IncludeCommand -> CommandResult
activate CommandResult

CommandResult --> IncludeCommand
deactivate CommandResult

IncludeCommand --> LogicManager : result
deactivate IncludeCommand

[<--LogicManager
deactivate LogicManager
@enduml
