@startuml
start
:User executes sort person command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([criterion prefix is valid])
    if() then ([only 1 criterion prefix is specified])
    :Sort person list based on
    the given criterion prefix;
    else ([else])
    :Gives an error that only 1 criterion prefix can be
    specified without changing the person list;
    endif
else ([else])
    :Gives an error that the criterion prefix is
    unrecognisable without changing the person list;
endif
stop
@enduml
