@startuml
start
:User executes sort person command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([exactly 1 criterion prefix is given, and it is valid])
    :Sort person list based on
    the given criterion prefix;
    :Display success message;
else ([else])
    :Gives an error that the command format is
    invalid without changing the person list;
endif
stop
@enduml
