@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InTrackParser" as InTrackParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant "st:SortTimeCommand" as SortTimeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort time a")
activate LogicManager

LogicManager -> InTrackParser : parseCommand("sort time a")
activate InTrackParser

create SortCommandParser
InTrackParser -> SortCommandParser
activate SortCommandParser

SortCommandParser --> InTrackParser
deactivate SortCommandParser

InTrackParser -> SortCommandParser : parse("time a")
activate SortCommandParser

create SortTimeCommand
SortCommandParser -> SortTimeCommand
activate SortTimeCommand

SortTimeCommand --> SortCommandParser : st
deactivate SortTimeCommand

SortCommandParser --> InTrackParser : st
deactivate SortCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SortCommandParser -[hidden]-> InTrackParser
destroy SortCommandParser

InTrackParser --> LogicManager : st
deactivate InTrackParser

LogicManager -> SortTimeCommand : execute()
activate SortTimeCommand

SortTimeCommand -> Model : ascendSortSalary()
activate Model

Model --> SortTimeCommand
deactivate Model

create CommandResult
SortTimeCommand -> CommandResult
activate CommandResult

CommandResult --> SortTimeCommand : result
deactivate CommandResult

SortTimeCommand --> LogicManager : result
deactivate SortTimeCommand

[<--LogicManager
deactivate LogicManager
@enduml
