@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class "{abstract}\nSortCommand" as SortCommand
Class SortByInterviewCommand
Class SortByDateCommand
Class SortByPositionCommand
Class SortByCompanyCommand

Class "<<interface>>\nParser" as Parser
Class SortCommandParser
Class ApplicationBookParser

SortCommand -up|> Command
SortCommandParser .up.> SortByInterviewCommand : creates >
SortCommandParser .up.> SortByDateCommand : creates >
SortCommandParser .up.> SortByPositionCommand : creates >
SortCommandParser .up.> SortByCompanyCommand : creates >

SortByInterviewCommand -up-|> SortCommand
SortByDateCommand -up-|> SortCommand
SortByPositionCommand -up-|> SortCommand
SortByCompanyCommand -up-|> SortCommand

SortCommandParser -left-|> Parser
ApplicationBookParser .left.> SortCommandParser : creates >
@enduml
