@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "HrPro Storage" #F4F6F6{
Class "<<interface>>\nHrProStorage" as HrProStorage
Class JsonHrProStorage
Class JsonSerializableHrPro
Class JsonAdaptedProject
Class JsonAdaptedTag
Class JsonAdaptedStaff
Class JsonAdaptedTask
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" HrProStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> HrProStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonHrProStorage .up.|> HrProStorage
JsonHrProStorage ..> JsonSerializableHrPro
JsonSerializableHrPro --> "*" JsonAdaptedProject
JsonAdaptedProject --> "*" JsonAdaptedTag
JsonSerializableHrPro --> "*" JsonAdaptedStaff
JsonSerializableHrPro --> "*" JsonAdaptedTask
JsonAdaptedStaff --> "*" JsonAdaptedTag
@enduml
