@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PropertyDirectory Storage" #F4F6F6{
Class "<<interface>>\nPropertyDirectoryStorage" as PropertyDirectoryStorage
Class JsonPropertyDirectoryStorage
Class JsonSerializablePropertyDirectory
Class JsonAdaptedProperty
Class JsonAdaptedTag
}

package "ClientDirectory Storage" #F4F6F6{
Class "<<interface>>\nClientDirectoryStorage" as ClientDirectoryStorage
Class JsonClientDirectoryStorage
Class JsonSerializableClientDirectory
Class JsonAdaptedClient
Class "JsonAdaptedTag" as JsonAdaptedTagForClient
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" PropertyDirectoryStorage
StorageManager -up-> "1" ClientDirectoryStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> PropertyDirectoryStorage
Storage -right-|> ClientDirectoryStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPropertyDirectoryStorage .up.|> PropertyDirectoryStorage
JsonPropertyDirectoryStorage ..> JsonSerializablePropertyDirectory
JsonSerializablePropertyDirectory --> "*" JsonAdaptedProperty
JsonAdaptedProperty --> "*" JsonAdaptedTag

JsonClientDirectoryStorage .up.|> ClientDirectoryStorage
JsonClientDirectoryStorage ..> JsonSerializableClientDirectory
JsonSerializableClientDirectory --> "*" JsonAdaptedClient
JsonAdaptedClient --> "*" JsonAdaptedTagForClient
@enduml
