@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Reminder Storage" #F4F6F6{
Class "<<interface>>\nReminderListStorage" as ReminderStorage
Class JsonReminderListStorage
Class JsonSerializableReminderList
Class JsonAdaptedReminder
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -left-> "1" UserPrefsStorage
StorageManager -right-> "1" AddressBookStorage
StorageManager -down-> "1 " ReminderStorage

Storage -down-|> UserPrefsStorage
Storage -down-|> AddressBookStorage
Storage -down-|> ReminderStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonReminderListStorage .up.|> ReminderStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonReminderListStorage ..> JsonSerializableReminderList
JsonSerializableReminderList --> "*" JsonAdaptedReminder

@enduml
