@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "Student, ModuleClass and Session" <<Rectangle>>{
Class "<<interface>>\nIdentity" as Identity
Class Student
Class ModuleClass {
    -className: String
}
Class Session {
    -sessionName: String
}
Class Date
Class StudentModuleData
Class SessionData {
    -grade: double
}
Class Address
Class Email
Class Name
Class Phone
}

Student *--> "1" Name
Student *--> "0..1" Address
Student *--> "0..1" Email
Student *--> "0..1" Phone
Student .up.|> Identity

ModuleClass "1" *--> "*" Session
ModuleClass .up.|> Identity

StudentModuleData .up.|> Identity
StudentModuleData "*" --> "1" ModuleClass

Student "1" *-up-> "*" StudentModuleData
StudentModuleData --> "*" SessionData

Session -right-> "1" Date
Session .up.|> Identity

SessionData .up.|> Identity
SessionData --> "1" Session


@enduml
