@startuml


Class "{abstract}\nUIPart"
Class PersonCard
Class PersonListPanel
Class PersonListViewCell
Class HBox
Class Label
Class FlowPane

"{abstract}\nUIPart" <|-- PersonCard
"{abstract}\nUIPart" <|-- PersonListPanel
PersonListViewCell ..> "*" PersonCard : setGraphic
"PersonCard" "0...1   " --> "*" "HBox"
"PersonCard" "0...1" --> "*" "Label"
"PersonCard" "   0...1" --> "*" "FlowPane"
PersonListPanel *-- PersonListViewCell

class PersonListViewCell {
updateItem(Person, boolean)
}




@enduml
