@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

Class "{abstract}\nUIPart" as UIPart
Class PersonCard
Class PersonListPanel
Class PersonListViewCell
Class HBox
Class Label
Class FlowPane

"UIPart" <|-- PersonCard
"UIPart" <|-- PersonListPanel
PersonListViewCell ..> "*" PersonCard : setGraphic
"PersonCard" " 0...1" -right-> "*" "HBox"
"PersonCard" "0...1" --> "*" "Label"
"PersonCard" "   0...1" --> "*" "FlowPane"
PersonListPanel *-- PersonListViewCell

class PersonListViewCell {
updateItem(Person, boolean)
}




@enduml
