@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TaskAddCommandParser" as TaskAddCommandParser LOGIC_COLOR
participant "m:TaskAddCommand" as TaskAddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("taskadd t/1 n/Create Feature A d/12-12-2022")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("taskadd t/1 n/Create Feature A d/12-12-2022")
activate AddressBookParser

create TaskAddCommandParser
AddressBookParser -> TaskAddCommandParser
activate TaskAddCommandParser

TaskAddCommandParser --> AddressBookParser
deactivate TaskAddCommandParser

AddressBookParser -> TaskAddCommandParser : parse("taskadd t/1 n/Create Feature A d/12-12-2022")
activate TaskAddCommandParser

create TaskAddCommand
TaskAddCommandParser -> TaskAddCommand
activate TaskAddCommand

TaskAddCommand --> TaskAddCommandParser : m
deactivate TaskAddCommand

TaskAddCommandParser --> AddressBookParser : m
deactivate TaskAddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TaskAddCommandParser -[hidden]-> AddressBookParser
destroy TaskAddCommandParser

AddressBookParser --> LogicManager :  m
deactivate AddressBookParser

LogicManager -> TaskAddCommand : execute()
activate TaskAddCommand

TaskAddCommand -> Model : addTask(1, "Create Feature A", "12-12-2022")
activate Model

Model --> TaskAddCommand
deactivate Model

create CommandResult
TaskAddCommand -> CommandResult
activate CommandResult

CommandResult --> TaskAddCommand
deactivate CommandResult

TaskAddCommand --> LogicManager : result
deactivate TaskAddCommand

[<--LogicManager
deactivate LogicManager
@enduml
