@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":UninurseBookParser" as UninurseBookParser LOGIC_COLOR
participant ":DisplayTasksGenericCommandParser" as DisplayTasksGenericCommandParser LOGIC_COLOR
participant ":TasksOnCommandParser" as TasksOnCommandParser LOGIC_COLOR
participant "<<class>>\nDateTime" as DateTimeClass LOGIC_COLOR
participant ":DateTime" as DateTime LOGIC_COLOR
participant "t:TasksOnCommand" as TasksOnCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view 22-10-2022")
activate LogicManager

LogicManager -> UninurseBookParser : parseCommand("view 22-10-2022")
activate UninurseBookParser

create DisplayTasksGenericCommandParser
UninurseBookParser -> DisplayTasksGenericCommandParser
activate DisplayTasksGenericCommandParser

create TasksOnCommandParser
DisplayTasksGenericCommandParser -> TasksOnCommandParser
activate TasksOnCommandParser

TasksOnCommandParser -> DateTimeClass : ofDate("22-10-2022")
activate DateTimeClass

create DateTime
DateTimeClass -> DateTime : new DateTime("22-10-2022")
activate DateTime

DateTime -> DateTimeClass : dt
deactivate DateTime

DateTimeClass -> TasksOnCommandParser : dt
deactivate DateTimeClass

TasksOnCommandParser -> TasksOnCommand : dt
activate TasksOnCommand

TasksOnCommand -> TasksOnCommandParser : t
deactivate TasksOnCommand

TasksOnCommandParser -> DisplayTasksGenericCommandParser : t
deactivate TasksOnCommandParser
destroy TasksOnCommandParser
DisplayTasksGenericCommandParser -> UninurseBookParser : t
deactivate DisplayTasksGenericCommandParser
destroy DisplayTasksGenericCommandParser

UninurseBookParser -> LogicManager : t
deactivate UninurseBookParser

LogicManager -> TasksOnCommand : execute()
activate TasksOnCommand

TasksOnCommand -> Model : setDayOfInterest(dt)
activate Model

Model -> TasksOnCommand
deactivate Model

create CommandResult
TasksOnCommand -> CommandResult
activate CommandResult

CommandResult --> TasksOnCommand : result
deactivate CommandResult

TasksOnCommand --> LogicManager : result
deactivate TasksOnCommand

[<--LogicManager
deactivate LogicManager
@enduml
