@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TutorialFilterCommandParser" as TutorialFilterCommandParser LOGIC_COLOR
participant ":TutorialFilterCommand" as TutorialFilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("tutorial filter g/T03")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("tutorial filter g/T03")
activate AddressBookParser

create TutorialFilterCommandParser
AddressBookParser -> TutorialFilterCommandParser
activate TutorialFilterCommandParser

TutorialFilterCommandParser --> AddressBookParser
deactivate TutorialFilterCommandParser

AddressBookParser -> TutorialFilterCommandParser : parse("T03")
activate TutorialFilterCommandParser

create TutorialFilterCommand
TutorialFilterCommandParser -> TutorialFilterCommand
activate TutorialFilterCommand

TutorialFilterCommand --> TutorialFilterCommandParser
deactivate TutorialFilterCommand

TutorialFilterCommandParser  --> AddressBookParser
deactivate TutorialFilterCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
TutorialFilterCommandParser  -[hidden]-> AddressBookParser
destroy TutorialFilterCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> TutorialFilterCommand : execute()
activate TutorialFilterCommand

TutorialFilterCommand -> Model : getFilteredStudentList()
activate Model

Model -> TutorialFilterCommand: student list
deactivate Model

create CommandResult
TutorialFilterCommand -> CommandResult
activate CommandResult

CommandResult --> TutorialFilterCommand
deactivate CommandResult

TutorialFilterCommand --> LogicManager : result
deactivate TutorialFilterCommand

[<--LogicManager
deactivate LogicManager
@enduml
