@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class ProfileSidePanel
Class TaskListPanel
Class StatusBar
Class CommandBox
Class ModuleCard
Class ModuleListPanel
Class TaskCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" StatusBar
MainWindow *-down-> "1" ProfileSidePanel
MainWindow *-down-> "1" TaskListPanel
MainWindow *-down-> "1" ModuleListPanel

ModuleListPanel o-down-> "*" ModuleCard
TaskListPanel o-down-> "*" TaskCard
MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
ModuleListPanel --|> UiPart
ModuleCard --|> UiPart
StatusBar --|> UiPart
ProfileSidePanel --|> UiPart
TaskListPanel --|> UiPart
TaskCard --|> UiPart
HelpWindow --|> UiPart

UiManager -right-> "1" Logic
UiManager -left-> Model
MainWindow ..> Model
MainWindow -left-> Logic

CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBar

MainWindow -[hidden]-|> UiPart
@enduml
