@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class TutorListPanel
Class ModuleListPanel
Class ModuleInfoPanel
Class ModulePanel
Class ScheduleListPanel
Class ScheduleGridPanel
Class StudentCard
Class TutorCard
Class ModuleCard
Class ModuleInfoCard
Class ScheduleCard
Class WeekdayCard
Class WeekdayCardVertical
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "2" TutorListPanel
MainWindow *-down-> "1" ModuleListPanel
MainWindow *-down-> "1" ModuleInfoPanel
MainWindow *-down-> "1" ModulePanel
MainWindow *-down-> "1" ScheduleListPanel
MainWindow *-down-> "1" ScheduleGridPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "0..1" HelpWindow

PersonListPanel -down-> "*" StudentCard
TutorListPanel -down-> "*" TutorCard
ModuleListPanel -down-> "*" ModuleCard
ModuleInfoPanel -down-> "*" StudentCard
ModulePanel -down-> "*" ModuleInfoCard
ScheduleListPanel -down-> "*" ScheduleCard
ScheduleGridPanel -down-> "*" WeekdayCard
ScheduleGridPanel -down-> "*" WeekdayCardVertical

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
StudentCard --|> UiPart
TutorCard --|> UiPart
ModuleCard --|> UiPart
ModuleInfoCard --|> UiPart
ScheduleCard --|> UiPart
WeekdayCard --|> UiPart
WeekdayCardVertical --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

StudentCard ..> Model
TutorCard ..> Model
ModuleInfoCard ..> Model
ModuleCard ..> Model
ScheduleCard ..> Model
WeekdayCard ..> Model
WeekdayCardVertical ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
