@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class TaskListPanel
Class TaskCard
Class StatusBarFooter
Class CommandBox
Class FilterStatusDisplay
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" TaskListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" FilterStatusDisplay
MainWindow --> "0..1" HelpWindow

TaskListPanel -down-> "*" TaskCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
TaskListPanel --|> UiPart
TaskCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

TaskCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

TaskListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
