@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class TutorListPanel
Class TutorCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" TutorListPanel

TutorListPanel -down-> "*" TutorCard

MainWindow -down-|> UiPart

TutorListPanel --|> UiPart
TutorCard --|> UiPart

TutorCard .right.> Model
UiManager -right-> Logic

MainWindow -[hidden]-|> UiPart
MainWindow -[hidden]-|> TutorListPanel
@enduml
