@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "clear"

package States <<rectangle>> {
    class State1 as "__pw0:PennyWise__" #FFF100
    class State2 as "__pw1:PennyWise__" #FFF100
    class State3 as "__pw2:PennyWise__" #FFF100
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State3
note right on link: State pw2 deleted.
@end
