@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command `delete -p 5`

package CommandQueue {
    class EmptyQueue
    class Command1 as "__deleteCommand:Command__"
    class Command2 as "__addCommand:Command__"
}
EmptyQueue -right-> Command1
Command1 -[hidden]right-> Command2
hide Command2

class Pointer as "Last Command" #FFFFFF
Pointer -up-> Command1
@end
