@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "task sort s/a"

package States <<rectangle>> {
    class State1 as "__tb0:TaskBook__"
    class State2 as "__tb1:TaskBook__"
    class State3 as "__tb2:TaskBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
