@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SoConnectParser" as SoConnectParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedSoConnect" as VersionedSoConnect MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> SoConnectParser : parseCommand(undo)
activate SoConnectParser

create UndoCommand
SoConnectParser -> UndoCommand
activate UndoCommand

UndoCommand --> SoConnectParser
deactivate UndoCommand

SoConnectParser --> LogicManager : u
deactivate SoConnectParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoSoConnect()
activate Model

Model -> VersionedSoConnect : undo()
activate VersionedSoConnect

VersionedSoConnect -> VersionedSoConnect :resetData(ReadOnlySoConnect)
VersionedSoConnect --> Model :
deactivate VersionedSoConnect

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
