@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WorkBookParser" as WorkBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedWorkBook" as VersionedWorkBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> WorkBookParser : parseCommand(undo)
activate WorkBookParser

create UndoCommand
WorkBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> WorkBookParser
deactivate UndoCommand

WorkBookParser --> LogicManager : u
deactivate WorkBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoWorkBook()
activate Model

Model -> VersionedWorkBook : undo()
activate VersionedWorkBook

VersionedWorkBook -> VersionedWorkBook :resetData(ReadOnlyWorkBook)
VersionedWorkBook --> Model :
deactivate VersionedWorkBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
