@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "add c/Apple p/Frontend Developer e/hr@apple.com w/https://www.apple.com/careers s/5000"

package States <<rectangle>> {
    class State1 as "__it0:InTrack__"
    class State2 as "__it1:InTrack__"
    class State3 as "__it2:InTrack__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State3
@end
