@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":SurvinParser" as SurvinParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedSurvin" as VersionedSurvin MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> SurvinParser : parseCommand(undo)
activate SurvinParser

create UndoCommand
SurvinParser -> UndoCommand
activate UndoCommand

UndoCommand --> SurvinParser
deactivate UndoCommand

SurvinParser --> LogicManager : u
deactivate SurvinParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoSurvin()
activate Model

Model -> VersionedSurvin : undo()
activate VersionedSurvin

VersionedSurvin -> VersionedSurvin :resetData(ReadOnlySurvin)
VersionedSurvin --> Model :
deactivate VersionedSurvin

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
