@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UnlinkExamCommandParser" as UnlinkExamCommandParser LOGIC_COLOR
participant "u:UnlinkExamCommand" as UnlinkExamCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "taskToUnlink:Task" as TaskToUnlink MODEL_COLOR
participant "unlinkedTask:Task" as UnlinkedTask MODEL_COLOR
end box

[-> LogicManager : execute("e unlink 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("e unlink 1")
activate AddressBookParser

create UnlinkExamCommandParser
AddressBookParser -> UnlinkExamCommandParser
activate UnlinkExamCommandParser

UnlinkExamCommandParser --> AddressBookParser
deactivate UnlinkExamCommandParser

AddressBookParser -> UnlinkExamCommandParser : parse("1")
activate UnlinkExamCommandParser

create UnlinkExamCommand
UnlinkExamCommandParser -> UnlinkExamCommand
activate UnlinkExamCommand

UnlinkExamCommand --> UnlinkExamCommandParser
deactivate UnlinkExamCommand

UnlinkExamCommandParser --> AddressBookParser : u
deactivate UnlinkExamCommandParser

UnlinkExamCommandParser -[hidden]-> AddressBookParser
destroy UnlinkExamCommandParser

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UnlinkExamCommand : execute()
activate UnlinkExamCommand

UnlinkExamCommand -> Model : getFilteredTaskList()
activate Model

Model --> UnlinkExamCommand
deactivate Model

UnlinkExamCommand -> TaskToUnlink : unlinkTask()
activate TaskToUnlink

create UnlinkedTask
TaskToUnlink -> UnlinkedTask
activate UnlinkedTask

UnlinkedTask --> TaskToUnlink
deactivate UnlinkedTask

TaskToUnlink --> UnlinkExamCommand : unlinkedTask
deactivate TaskToUnlink

UnlinkExamCommand -> Model : replaceTask(taskToUnlink, unlinkedTask, true)
activate Model

Model --> UnlinkExamCommand
deactivate Model

create CommandResult
UnlinkExamCommand -> CommandResult : CommandResult(EXAM_UNLINKED_SUCCESS)
activate CommandResult

CommandResult --> UnlinkExamCommand
deactivate CommandResult

UnlinkExamCommand --> LogicManager : result
deactivate UnlinkExamCommand

UnlinkExamCommand -[hidden]-> LogicManager
destroy UnlinkExamCommand

[<--LogicManager
deactivate LogicManager

@enduml
