@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "mark 1"

package previousCommands {
    class PreviousCommand1 as "ls -u"
    class PreviousCommand2 as " mark 1 "
    class PreviousCommand3 as " "
}

PreviousCommand1 -[hidden]right-> PreviousCommand2
PreviousCommand2 -[hidden]right-> PreviousCommand3

class Pointer as "pointer" #FFFFFF
Pointer -up-> PreviousCommand3
@enduml
