@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor BLACK
skinparam classBackgroundColor STORAGE_COLOR
skinparam classAttributeIconSize 0

package Storage {
class StorageManager
}

@enduml
