@startuml

start

if () then ([inputs are valid))
    switch ()
    case ([entry type is income])
      :Retrieve the list of income;
    case ([entry type is expenditure])
      :Retrieve the list of expenditure;
    case ([else])
      :Display an error message;
      stop
    endswitch

    if () then ([year-month is specified)
        :Display the list of entries in the year-month;
        :Display line chart of amount statistic\nof the entries in the year-month;
    else ([else])
        :Display the list of entries;
        :Display pie chart of the entries\nbased on all categories;
    endif
else ([else])
    stop
endif

stop

@enduml


