@startuml
!include style.puml

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow LOGIC_COLOR
participant ":TutorDetailsPanel" as TutorDetailsPanel LOGIC_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TuthubParser" as TuthubParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant ":ViewCommand" as ViewCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> MainWindow : executeCommand("view 1")
activate MainWindow

MainWindow -> LogicManager : execute("view 1")
activate LogicManager

LogicManager -> TuthubParser : parseCommand("view 1")
activate TuthubParser

create ViewCommandParser
TuthubParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> TuthubParser
deactivate ViewCommandParser

TuthubParser -> ViewCommandParser : parse("1")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser
deactivate ViewCommand

ViewCommandParser --> TuthubParser
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> TuthubParser
destroy ViewCommandParser

TuthubParser --> LogicManager
deactivate TuthubParser

LogicManager --> ViewCommand : execute()
activate ViewCommand

ViewCommand -> Model : setTutorToView(tutorToView)
activate Model

Model --> ViewCommand
deactivate Model

create CommandResult
ViewCommand -> CommandResult
activate CommandResult

CommandResult --> ViewCommand : result
deactivate CommandResult

ViewCommand --> LogicManager : result
deactivate ViewCommand

LogicManager --> MainWindow : result
deactivate LogicManager

MainWindow --> CommandResult : isView()
activate CommandResult

CommandResult --> MainWindow : true
deactivate CommandResult

MainWindow -> LogicManager : getTutorToView()
activate LogicManager

LogicManager -> Model : getTutorToView()
activate Model

Model --> LogicManager : tutorToView
deactivate Model

LogicManager -> MainWindow : tutorToView
deactivate LogicManager

MainWindow --> MainWindow : handleView(tutorToView)
activate MainWindow

create TutorDetailsPanel
MainWindow --> TutorDetailsPanel : tutorToView
activate TutorDetailsPanel

TutorDetailsPanel --> MainWindow
deactivate TutorDetailsPanel

MainWindow --> MainWindow
deactivate MainWindow
[<- MainWindow
@enduml
