@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant ":ViewCommandParser" as ViewCommandParser LOGIC_COLOR
participant "v:ViewCommand" as ViewCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p:ExactMatchPredicate" as Predicate MODEL_COLOR
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view 1")
activate LogicManager

LogicManager -> InternshipBookParser : parseCommand("view 1")
activate InternshipBookParser

create ViewCommandParser
InternshipBookParser -> ViewCommandParser
activate ViewCommandParser

ViewCommandParser --> InternshipBookParser
deactivate ViewCommandParser

InternshipBookParser -> ViewCommandParser : parse("1")
activate ViewCommandParser

create ViewCommand
ViewCommandParser -> ViewCommand
activate ViewCommand

ViewCommand --> ViewCommandParser : v
deactivate ViewCommand

ViewCommandParser --> InternshipBookParser : v
deactivate ViewCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewCommandParser -[hidden]-> InternshipBookParser
destroy ViewCommandParser

InternshipBookParser --> LogicManager : v
deactivate InternshipBookParser

LogicManager -> ViewCommand : execute()
activate ViewCommand

create Predicate
ViewCommand -> Predicate
activate Predicate

Predicate --> ViewCommand : p
deactivate Predicate

ViewCommand -> Model : updateViewItem(p)
activate Model

Model --> ViewCommand
deactivate Model

ViewCommand --> LogicManager : result
deactivate ViewCommand
ViewCommand -[hidden]-> LogicManager
destroy ViewCommand

[<--LogicManager
deactivate LogicManager
@enduml
