@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MyInsuRecParser" as MyInsuRecParser LOGIC_COLOR
participant "command:ViewClientCommand" as ViewClientCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("viewClient i/1")
activate LogicManager

LogicManager -> MyInsuRecParser : parseCommand("viewClient i/1")
activate MyInsuRecParser

create ViewClientCommand
MyInsuRecParser -> ViewClientCommand
activate ViewClientCommand

ViewClientCommand --> MyInsuRecParser : command
deactivate ViewClientCommand

MyInsuRecParser --> LogicManager : command
deactivate MyInsuRecParser

LogicManager -> ViewClientCommand : execute()
activate ViewClientCommand

ViewClientCommand -> Model : model.getFilteredClientList()
activate Model

Model --> ViewClientCommand : clientList
deactivate Model

ViewClientCommand --> ViewClientCommand : Get client

create CommandResult
ViewClientCommand -> CommandResult
activate CommandResult

CommandResult --> ViewClientCommand : result
deactivate CommandResult

ViewClientCommand --> LogicManager : result
deactivate ViewClientCommand

[<--LogicManager
deactivate LogicManager
@enduml
