@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":JeeqTrackerParser" as JeeqTrackerParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "d:EditTransactionCommand" as EditTransactionCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Client" as Client MODEL_COLOR
participant ":TransactionLog" as TransactionLog MODEL_COLOR
end box

[-> LogicManager : execute("edit 1 m/transaction g/Apple price/5")
activate LogicManager

LogicManager -> JeeqTrackerParser : parseCommand("edit")
activate JeeqTrackerParser

create EditCommandParser
JeeqTrackerParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> JeeqTrackerParser
deactivate EditCommandParser

JeeqTrackerParser -> EditCommandParser : parse("1 m/transaction g/Apple price/5")
activate EditCommandParser

create EditTransactionCommand
EditCommandParser -> EditTransactionCommand
activate EditTransactionCommand

EditTransactionCommand --> EditCommandParser : d
deactivate EditTransactionCommand

EditCommandParser --> JeeqTrackerParser : d
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> JeeqTrackerParser
destroy EditCommandParser

JeeqTrackerParser --> LogicManager : d
deactivate JeeqTrackerParser

LogicManager -> EditTransactionCommand : execute()
activate EditTransactionCommand

EditTransactionCommand -> Model : getFilteredClientList()
activate Model

Model --> EditTransactionCommand
deactivate Model

EditTransactionCommand -> Client : getTransactions()
activate Client

Client --> EditTransactionCommand
deactivate Client

EditTransactionCommand -> TransactionLog : setTransaction(1, editedTransaction)
activate TransactionLog

TransactionLog --> EditTransactionCommand
deactivate TransactionLog

EditTransactionCommand -> Model: updateFilteredClientList
activate Model

Model --> EditTransactionCommand
deactivate Model

create CommandResult
EditTransactionCommand -> CommandResult
activate CommandResult

CommandResult --> EditTransactionCommand
deactivate CommandResult

EditTransactionCommand --> LogicManager : result
deactivate EditTransactionCommand

[<--LogicManager
deactivate LogicManager
@enduml
