@startuml
!include ../style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":TaskBookParser" as abp LOGIC_COLOR
Participant ":ContactEditCommandParser" as ecp LOGIC_COLOR
Participant "command:ContactEditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create ecp
abp -> ecp
abp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editPersonDescriptor
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command

@enduml
