package seedu.address.model.quote;

import java.util.concurrent.ThreadLocalRandom;

/** Collection of quotes. */
public class QuoteList {
    private static Quote randomQuote;
    private static Quote[] quotes = {
        new Quote("If they wrote it to make money, don't read it.",
                "Naval Ravikant"),
        new Quote("Lying can never save us from another lie.",
                "Vaclav Havel"),
        new Quote("The only limits in our life are those we impose on ourselves.",
                "Bob Proctor"),
        new Quote("The more we have the less we own.",
                "Meister Eckhart"),
        new Quote("Words can only have a positive effect on others if and when they are ready to listen.",
                "Christopher Reeve"),
        new Quote("Do not use life to give life to death. Do not use death to bring death to life.",
                "Zhuangzi"),
        new Quote(
                "Show kindness but never expect it. Show authenticity but never expect it. "
                        + "Only the wise are indifferent to things they can't control.",
                "Maxime Lagace"),
        new Quote("You don't need a weatherman to know which way the wind blows.",
                "Bob Dylan"),
        new Quote("A journey of a thousand miles must begin with a single step.",
                "Lao Tzu"),
        new Quote("Thinking is the hardest work there is. That is why so few people engage in it.",
                "Robert Kiyosaki"),
        new Quote("Make each day your masterpiece.",
                "John Wooden"),
        new Quote("The more you give, the more comes back to you.",
                "Napoleon Hill"),
        new Quote("Peace is letting it be. Letting life flow, letting emotions flow through you.",
                "Kamal Ravikant"),
        new Quote(
                "An approximate answer to the right question is worth a great deal more than "
                        + "a precise answer to the wrong question.",
                "John Tukey"),
        new Quote("Life can only be understood backwards; but it must be lived forwards.",
                "Soren Kierkegaard"),
        new Quote("Do you want to know who you are? Don't ask. Act! Action will delineate and define you.",
                "Thomas Jefferson"),
        new Quote("Success is good at any age, but the sooner you find it, the longer you will enjoy it.",
                "Napoleon Hill"),
        new Quote(
                "A simple rule in dealing with those who are hard to get along with is to remember that this person "
                        + "is striving to assert his superiority; and you must deal with him from that point of view.",
                "Alfred Adler"),
        new Quote("We can know only that we know nothing. And that is the highest degree of human wisdom.",
                "Leo Tolstoy"),
        new Quote("You can't wait for inspiration. You have to go after it with a club. ",
                "Jack London"),
        new Quote("There is nothing more truly artistic than to love people.",
                "Vincent van Gogh"),
        new Quote(
                "Trying to predict the future is like trying to drive down a country road "
                        + "at night with no lights while looking out the back window.",
                "Peter Drucker"),
        new Quote(
                "Patience is a form of wisdom. It demonstrates that we understand and "
                        + "accept the fact that sometimes things must unfold in their own time.",
                "Jon Kabat-Zinn"),
        new Quote(
                "When something comes from within, when it is a part of you, you have "
                        + "no choice but to live it, to express it.",
                "Kamal Ravikant"),
        new Quote("Decide what your truth is. Then live it.",
                "Kamal Ravikant"),
        new Quote("Never fear quarrels, but seek hazardous adventures.",
                "Alexandre Dumas"),
        new Quote(
                "If you put yourself in a position where you have to stretch outside "
                        + "your comfort zone, then you are forced to expand your consciousness.",
                "Unknown"),
        new Quote("A day without laughter is a day wasted.",
                "Charlie Chaplin"),
        new Quote(
                "Time and health are two precious assets that we don't recognize "
                        + "and appreciate until they have been depleted. ",
                "Denis Waitley"),
        new Quote("All power is from within and therefore under our control.",
                "Robert Collier"),
        new Quote(
                "Many of life's failures are people who did not realize how "
                        + "close they were to success when they gave up.",
                "Thomas Edison"),
        new Quote("Less is more.",
                "Robert Browning"),
        new Quote("Hope means hoping when everything seems hopeless.",
                "Gilbert Chesterton"),
        new Quote("Failure is just information and an opportunity to change your course.",
                "Oprah Winfrey"),
        new Quote("Never allow a person to tell you no who doesn't have the power to say yes.",
                "Eleanor Roosevelt"),
        new Quote("Fear does not have any special power unless you empower it by submitting to it.",
                "Les Brown"),
        new Quote("Reversing your treatment of the man you have wronged is better than asking his forgiveness.",
                "Elbert Hubbard"),
        new Quote("The ones who are crazy enough to think they can change the world, are the ones that do.",
                "Steve Jobs"),
        new Quote("Words have no power to impress the mind without the exquisite horror of their reality.",
                "Edgar Allan Poe"),
        new Quote("Don't let someone elses. opinion become your reality.",
                "Les Brown"),
        new Quote("From error to error one discovers the entire truth.",
                "Sigmund Freud"),
        new Quote("Looking after my health today gives me a better hope for tomorrow. ",
                "Anne Wilson Schaef"),
        new Quote(
                "Men learn to love the woman they are attracted to. "
                        + "Women learn to become attracted to the man they fall in love with.",
                "Woody Allen"),
        new Quote("Life doesn't get easier or more forgiving, we get stronger and more resilient.",
                "Steve Maraboli"),
        new Quote(
                "Respect other people's feelings. It might mean nothing to you, but it could mean everything to them.",
                "Roy T. Bennett"),
        new Quote("I defeat my enemies when I make them my friends.",
                "Dalai Lama"),
        new Quote("If you want others to be happy, practice compassion. If you want to be happy, practice compassion.",
                "Dalai Lama"),
        new Quote("We don't stop playing because we grow old; we grow old because we stop playing.",
                "George Bernard Shaw"),
        new Quote("Champions keep playing until they get it right.",
                "Billie Jean King"),
        new Quote("Life happens in the river, not the shore.",
                "Maxime Lagace"),
        new Quote("Adventure is worthwhile in itself.",
                "Amelia Earhart"),
        new Quote(
                "Bad things are not the worst things that an happen to us. "
                        + "NOTHING is the worst thing that can happen to us.",
                "Richard Bach"),
        new Quote("You cannot have a positive life and a negative mind.",
                "Joyce Meyer"),
        new Quote("Of all men's miseries the bitterest is this: to know so much and to have control over nothing. ",
                "Herodotus"),
        new Quote(
                "When you say yes to change, you are choosing to navigate that path peacefully and happily "
                        + "and see where it takes you.",
                "Sonia Ricotti"),
        new Quote("I think self-awareness is probably the most important thing towards being a champion. ",
                "Billie Jean King"),
        new Quote("Always do your best. What you plant now, you will harvest later.",
                "Og Mandino"),
        new Quote("It is easy to discover what another has discovered before.",
                "Christopher Columbus"),
        new Quote("What are we doing here, that is the question.",
                "Samuel Beckett"),
        new Quote("Courage is fear that has said its prayers and decided to go forward anyway.",
                "Joyce Meyer"),
        new Quote(
                "The more you are focused on time - past and future - the more you miss the Now, "
                        + "the most precious thing there is.",
                "Eckhart Tolle"),
        new Quote("When you judge others, you do not define them, you define yourself.",
                "Earl Nightingale"),
        new Quote("Today is the oldest you've ever been, and the youngest you'll ever be again.",
                "Eleanor Roosevelt"),
        new Quote("The reward of suffering is experience.",
                "Harry S. Truman"),
        new Quote(
                "Most people achieved their greatest success one step beyond what looked like their greatest failure.",
                "Brian Tracy"),
        new Quote("The more you praise and celebrate your life, the more there is in life to celebrate. ",
                "Oprah Winfrey"),
        new Quote("Within every desire is the mechanics of its fulfillment.",
                "Deepak Chopra"),
        new Quote("Don't concern yourself with the money. Be of service. Build. Work. Dream. Create.",
                "Earl Nightingale"),
        new Quote("The people who succeed are irrationally passionate about something.",
                "Naval Ravikant"),
        new Quote("Every day may not be good, but there's something good in every day.",
                "Unknown"),
        new Quote("If you let your head get too big, it'll break your neck.",
                "Elvis Presley"),
        new Quote("If you're waiting until you feel talented enough to make it, you'll never make it.",
                "Criss Jami"),
        new Quote("What we dwell on is who we become.",
                "Oprah Winfrey"),
        new Quote("If you want peace, accept. If you want suffering, expect.",
                "Maxime Lagace"),
        new Quote(
                "There's no scarcity of opportunity to make a living at what you love. "
                        + "There is only a scarcity of resolve to make it happen.",
                "Wayne Dyer"),
        new Quote("Everyone thinks of changing the world, but no one thinks of changing himself.",
                "Leo Tolstoy"),
        new Quote(
                "Happiness comes when you believe in what you are doing, know what you are doing, "
                        + "and love what you are doing.",
                "Brian Tracy"),
        new Quote("Perfection is not attainable, but if we chase perfection we can catch excellence.",
                "Vince Lombardi"),
        new Quote("Once you choose hope, anything's possible.",
                "Christopher Reeve"),
        new Quote("The older you get, the better you get. Unless you're a banana.",
                "Betty White"),
        new Quote("We learn by pushing ourselves and finding what really lies at the outer reaches of our abilities.",
                "Josh Waitzkin"),
        new Quote("Why fit in when you were born to stand out?",
                "Dr. Seuss"),
        new Quote("Take interest and even delight in doing the small things well.",
                "Jim Rohn"),
        new Quote("Difficult and meaningful will always bring more satisfaction than easy and meaningless.",
                "Maxime Lagace"),
        new Quote("People don't care how much you know until they know how much you care.",
                "Theodore Roosevelt"),
        new Quote("Walking with a friend in the dark is better than walking alone in the light.",
                "Helen Keller"),
        new Quote("You don't earn loyalty in a day. You earn loyalty day-by-day.",
                "Jeffrey Gitomer"),
        new Quote(
                "Resentment or grudges do no harm to the person against whom you hold these feelings "
                        + "but every day and every night of your life, they are eating at you.",
                "Norman Vincent Peale"),
        new Quote("Only put off until tomorrow what you are willing to die having left undone.",
                "Pablo Picasso"),
        new Quote("How people treat you is their karma; how you react is yours. ",
                "Wayne Dyer"),
        new Quote("All that a man achieves and all that he fails to achieve is the direct result of his own thoughts.",
                "James Allen"),
        new Quote(
                "You must live in the present, launch yourself on every wave, find your eternity in each moment. "
                        + "Fools stand on their island of opportunities and look toward another land. "
                        + "There is no other land; there is no other life but this.",
                "Henry David Thoreau"),
        new Quote("If you spend too much time thinking about a thing, you'll never get it done. ",
                "Bruce Lee"),
        new Quote("Our greatest fears lie in anticipation.",
                "Honore de Balzac"),
        new Quote("Adults are just children who earn money.",
                "Kenneth Branagh"),
        new Quote("Happiness is a choice, not a result. Nothing will make you happy until you choose to be happy.",
                "Ralph Marston"),
        new Quote(
                "First comes the shy wish. Then you must have the heart to have the dream. Then, you work, and work.  ",
                "Estee Lauder"),
        new Quote("Do good by stealth, and blush to find it fame.",
                "Alexander Pope"),
        new Quote("It doesn't matter how slow you go, as long as you don't stop.",
                "Confucius"),
        new Quote("Life is about choice. You can choose to be a victim or anything else you like to be.",
                "Celestine Chua"),
        new Quote("The longer we dwell on our misfortunes, the greater is their power to harm us.",
                "Voltaire"),
        new Quote("The eye with which I see God is the same eye with which God sees me.",
                "Meister Eckhart"),
        new Quote("You are what you believe yourself to be.",
                "Paulo Coelho"),
        new Quote("The important thing is not what one is born with but what use one makes of that equipment.",
                "Alfred Adler"),
        new Quote("Do all things with love.",
                "Og Mandino"),
        new Quote("Success is built sequentially. It's one thing at a time.",
                "Gary Keller"),
        new Quote("The future is not a gift. It is an achievement.",
                "Robert F. Kennedy"),
        new Quote("The best fighter is never angry.",
                "Lao Tzu"),
        new Quote("Where you are right now doesn't have to determine where you'll end up.",
                "Barack Obama"),
        new Quote("We are all in the gutter, but some of us are looking at the stars. ",
                "Oscar Wilde"),
        new Quote("The best way out is always through.",
                "Robert Frost"),
        new Quote(
                "If you are not living each day with excitement, energy, and passion, then you are not living true "
                        + "to your life purpose.",
                "Celestine Chua"),
        new Quote("Eighty percent of success is showing up. ",
                "Woody Allen"),
        new Quote("Like it or not, this moment is all we really have to work with.",
                "Jon Kabat-Zinn"),
        new Quote("Death and life have their determined appointments; riches and honors depend upon heaven. ",
                "Confucius"),
        new Quote(
                "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to "
                        + "do what you believe is great work. ",
                "Steve Jobs"),
        new Quote("We can either add to our character each day, or we can fritter away our energies in distractions.",
                "Ming-Dao Deng"),
        new Quote("Do not regret the past. Look to the future.",
                "Soyen Shaku"),
        new Quote("Faith is taking the first step even when you don't see the whole staircase.",
                "Martin Luther King, Jr."),
        new Quote("You are today where your thoughts have brought you.",
                "James Allen"),
        new Quote(
                "Life goes by very fast. And the worst thing in life that you can have is a job that you hate, and "
                        + "have no energy and creativity in.",
                "Robert Greene"),
        new Quote("Make your stand today. On this spot. On this day.",
                "Ming-Dao Deng"),
        new Quote(
                "There can be no greater gift than that of giving one's time and energy to help others without "
                        + "expecting anything in return.",
                "Nelson Mandela"),
        new Quote("A tiger doesn't lose sleep over the opinion of sheep.",
                "Shahir Zag"),
        new Quote("A fall into a ditch makes you wiser.",
                "Chinese Proverb"),
        new Quote("A loving heart is the truest wisdom.",
                "Charles Dickens"),
        new Quote("If you have to be in a soap opera try not to be cast in the worst role.",
                "Judy Garland"),
        new Quote("The fastest way to change is to laugh at your own folly.",
                "Spencer Johnson"),
        new Quote("He suffers more than necessary, who suffers before it is necessary.  ",
                "Seneca"),
        new Quote("All you need is passion. If you have a passion for something, you'll create the talent.",
                "Yanni"),
        new Quote("No great mind has ever existed without a touch of madness.",
                "Aristotle"),
        new Quote("Learning never exhausts the mind. ",
                "Leonardo da Vinci"),
        new Quote("Until you change how you get things done, you'll never know what works best.",
                "Roy T. Bennett"),
        new Quote("Work as though you would live forever, and live as though you would die today. Go another mile.",
                "Og Mandino"),
        new Quote("I will not walk backward in life.",
                "J.R.R. Tolkien"),
        new Quote("Without education, we are in a horrible and deadly danger of taking educated people seriously.",
                "Gilbert Chesterton"),
        new Quote("To live outside the law, you must be honest. ",
                "Bob Dylan"),
        new Quote("What loneliness is more lonely than distrust?",
                "George Eliot"),
        new Quote(
                "Hope itself is like a star- not to be seen in the sunshine of prosperity, and only to be "
                        + "discovered in the night of adversity.",
                "Charles Spurgeon"),
        new Quote("High thoughts must have high language.",
                "Aristophanes"),
        new Quote("Everybody's life is either rewarding or an example.",
                "Tony Robbins"),
        new Quote(
                "Life is about accepting the challenges along the way, choosing to keep moving forward, "
                        + "and savoring the journey.",
                "Roy T. Bennett"),
        new Quote("It is the power of thought that gives man power over nature.",
                "Hans Christian Andersen"),
        new Quote("Don't let what you cannot do interfere with what you can do.",
                "John Wooden"),
        new Quote("Admire as much as you can. Most people do not admire enough.",
                "Vincent van Gogh"),
        new Quote("Less is more.",
                "Robert Browning"),
        new Quote("Peace is not the absence of conflict, but the ability to cope with it.",
                "Unknown"),
        new Quote(
                "If life is a video game, the graphics are great, but the plot is confusing and the tutorial "
                        + "is way too long.",
                "Elon Musk"),
        new Quote("It is literally true that you can succeed best and quickest by helping others succeed.",
                "Napoleon Hill"),
        new Quote("Be kind, for everyone you meet is fighting a harder battle.",
                "Plato"),
        new Quote(
                "Having an open mind is one of the most important qualities we can possess. Once our minds "
                        + "close, we stop evolving.",
                "Yanni"),
        new Quote("The secret of life is to fall seven times and to get up eight times.",
                "Paulo Coelho"),
        new Quote(
                "Courage is what it takes to stand up and speak. Courage is also what it takes to sit down and listen.",
                "Winston Churchill"),
        new Quote("Failure is an option, fear is not.",
                "James Cameron"),
        new Quote("Decide upon your major definite purpose in life and then organize all your activities around it.",
                "Brian Tracy"),
        new Quote("I am always doing what I cannot do yet, in order to learn how to do it.",
                "Vincent van Gogh"),
        new Quote("Success is an iceberg.",
                "Unknown"),
        new Quote("He who possesses most must be most afraid of loss.",
                "Leonardo da Vinci"),
        new Quote("Your happiness is what truly matters most. Do what you have to do in order to be happy.",
                "Brian Tracy"),
        new Quote("The path is difficult to ensure worthiness. The lazy look elsewhere, The persevering find riches.",
                "Ming-Dao Deng"),
        new Quote("Your worth consists in what you are and not in what you have.",
                "Thomas Edison"),
        new Quote("Learn only how to avoid seeking for and attaching yourselves to anything.",
                "Huang Po"),
        new Quote(
                "When you are able to employ your will always for constructive purposes, you become the "
                        + "controller of your destiny.",
                "Paramahansa Yogananda"),
        new Quote("Words can only have a positive effect on others if and when they are ready to listen.",
                "Christopher Reeve"),
        new Quote("Chop your own wood and it will warm you twice. ",
                "Henry Ford"),
        new Quote("The purpose of life is the expansion of happiness.",
                "Deepak Chopra"),
        new Quote(
                "Bad things are not the worst things that an happen to us. NOTHING is the worst thing that "
                        + "can happen to us.",
                "Richard Bach"),
        new Quote("Never fear quarrels, but seek hazardous adventures.",
                "Alexandre Dumas"),
        new Quote("The key to success is action.",
                "Brian Tracy"),
        new Quote("Believe that life is worth living and your belief will help create the fact.",
                "William James"),
        new Quote("Freedom lies in being bold.",
                "Robert Frost"),
        new Quote("The ability to observe without evaluating is the highest form of intelligence.",
                "Jiddu Krishnamurti"),
        new Quote("To lead the people, walk behind them.",
                "Lao Tzu"),
        new Quote(
                "Rather than waste time and energy worrying, use that time and energy to constructively deal "
                        + "with whatever is causing the worry.",
                "Celestine Chua"),
        new Quote("A poet should be so crafty with words that he is envied even for his pains.",
                "Criss Jami"),
        new Quote(
                "If you love somebody, let them go, for if they return, they were always yours. If they don't, "
                        + "they never were.",
                "Kahlil Gibran"),
        new Quote("You have the potential for greatness.",
                "Steve Harvey"),
        new Quote("Go confidently in the direction of your dreams! Live the life you've imagined.",
                "Henry David Thoreau"),
        new Quote(
                "Everyone faces challenges in life. It's a matter of how you learn to overcome them and using them "
                        + "to your advantage.",
                "Celestine Chua"),
        new Quote("Don't give up on your dreams, or your dreams will give up on you.",
                "John Wooden"),
        new Quote("Make yourself so useful to other people, that they think you are irreplaceable.",
                "Og Mandino"),
        new Quote("Heroes don't need to talk about what they did.",
                "W.P. Kinsella"),
        new Quote("Insanity: doing the same thing over and over again and expecting different results.",
                "Albert Einstein"),
        new Quote("Fear can hold you prisoner. Hope can set you free.",
                "Stephen King"),
        new Quote("The destiny of man is in his own soul. ",
                "Herodotus"),
        new Quote("Treat every moment as your last. It is not preparation for something else.",
                "Shunryu Suzuki"),
        new Quote("He who permits himself to tell a lie once, finds it much easier to do it the second time.",
                "Thomas Jefferson"),
        new Quote("Do the hard jobs first. The easy jobs will take care of themselves.",
                "Dale Carnegie"),
        new Quote(
                "No experience is a cause of success or failure. We do not suffer from the shock of our experiences, "
                        + "so-called trauma - but we make out of them just what suits our purposes.",
                "Alfred Adler"),
        new Quote("To improve is to change, so to be perfect is to change often.",
                "Winston Churchill"),
        new Quote("Life belongs to the living, and he who lives must be prepared for changes.",
                "Johann Wolfgang von Goethe"),
        new Quote("The truth is simple. If it was complicated, everyone would understand it.",
                "Walt Whitman"),
        new Quote("Do not go where the path may lead, go instead where there is no path and leave a trail.",
                "Ralph Waldo Emerson"),
        new Quote("Confidence is the greatest friend.",
                "Lao Tzu"),
        new Quote("If you genuinely want something, don't wait for it - teach yourself.",
                "Gurbaksh Chahal"),
        new Quote("Most people spend more time and energy going around problems than in trying to solve them. ",
                "Henry Ford"),
        new Quote("You can have it all. You just can't have it all at once. ",
                "Oprah Winfrey"),
        new Quote(
                "As long as a human being worries about when he will die, and what he has that is his, "
                        + "all of his works are zero.",
                "Kabir"),
        new Quote(
                "A life spent making mistakes is not only more honorable but more useful than a life spent "
                        + "doing nothing.",
                "George Bernard Shaw"),
        new Quote("The score never interested me, only the game.",
                "Mae West"),
        new Quote("Don't let the past steal your present.",
                "Cherralea Morgen"),
        new Quote("Life is not meant to be easy my child, but take courage: it can be delightful.",
                "George Bernard Shaw"),
        new Quote("Love is the energy of life.",
                "Robert Browning"),
        new Quote("Act the way you want to be and soon you'll be the way you act.",
                "Les Brown"),
        new Quote("Enjoy life. There's plenty of time to be dead.",
                "Hans Christian Andersen"),
        new Quote("High thoughts must have high language.",
                "Aristophanes"),
        new Quote("The more something threatens your identity, the more you will avoid it.",
                "Mark Manson"),
        new Quote("Success is not how high you have climbed, but how you make a positive difference to the world.",
                "Roy T. Bennett"),
        new Quote("Do not allow your inner doubts to keep you from achieving what you can do.",
                "Lolly Daskal"),
        new Quote("There are no ordinary moments.",
                "Dan Millman"),
        new Quote("Be approximately right rather than exactly wrong.",
                "John Tukey"),
        new Quote("Do not follow the ideas of others, but learn to listen to the voice within yourself.",
                "Dogen"),
        new Quote("The older you get the stronger the wind gets - and it's always in your face.",
                "Pablo Picasso"),
        new Quote("Don't let the silly little dramas of each day get you down. For you are here to do great things.",
                "Ralph Marston"),
        new Quote("Life goes by fast. Enjoy it. Calm down. It's all funny.",
                "Joan Rivers"),
        new Quote("The universe doesn't allow perfection.",
                "Stephen Hawking"),
        new Quote("The path is difficult to ensure worthiness. The lazy look elsewhere, The persevering find riches.",
                "Ming-Dao Deng"),
        new Quote(
                "Move out of your comfort zone. You can only grow if you are willing to feel awkward and "
                        + "uncomfortable when you try something new.",
                "Brian Tracy"),
        new Quote("Everything has beauty but not everyone sees it.",
                "Confucius"),
        new Quote("Work is always an antidote to depression.",
                "Eleanor Roosevelt"),
        new Quote("The most important things are the hardest to say.",
                "Stephen King"),
        new Quote("Never lose hope. Storms make people stronger and never last forever.",
                "Roy T. Bennett"),
        new Quote("Misfortune shows those who are not really friends.",
                "Aristotle"),
        new Quote(
                "If you hang out with chickens, you're going to cluck and if you hang out with eagles, "
                        + "you're going to fly.",
                "Steve Maraboli"),
        new Quote("What one does is what counts. Not what one had the intention of doing.",
                "Pablo Picasso"),
        new Quote("You will succeed because most people are lazy.",
                "Shahir Zag"),
        new Quote("The four P's to success are pressure, persistence, perseverance, and prayer.",
                "Steve Harvey"),
        new Quote("Before you can see the Light, you have to deal with the darkness.",
                "Dan Millman"),
        new Quote("Fear not the path of Truth for the lack of People walking on it.",
                "Robert F. Kennedy"),
        new Quote("Dream big. Start small. But most of all, start.",
                "Simon Sinek"),
        new Quote("Distant water does not put out a nearby fire.",
                "Chinese Proverb"),
        new Quote(
                "Death is as sure for that which is born, as birth is for that which is dead. Therefore "
                        + "grieve not for what is inevitable.",
                "Bhagavad Gita"),
        new Quote(
                "Your task is not to seek for love, but merely to seek and find all the barriers within "
                        + "yourself that you have built against it.",
                "Rumi"),
        new Quote("A zen master's life is one continuous mistake.",
                "Dogen"),
        new Quote("Normal is the average of deviance.",
                "Rita Mae Brown"),
        new Quote("Life is a question and how we live it is our answer.",
                "Gary Keller"),
        new Quote("Once you learn to quit, it becomes a habit.",
                "Vince Lombardi"),
        new Quote(
                "Become the kind of leader that people would follow voluntarily, even if you had no title or position.",
                "Brian Tracy"),
        new Quote("If you pray for rain, be prepared to deal with some mud.",
                "Mary Engelbreit"),
        new Quote("We must learn to live together as brothers or perish together as fools.",
                "Martin Luther King, Jr."),
        new Quote("Ability is a poor man's wealth.",
                "John Wooden"),
        new Quote("True life is lived when tiny changes occur.",
                "Leo Tolstoy"),
        new Quote("Nature loves to hide.",
                "Heraclitus"),
        new Quote("A wise man can learn more from a foolish question than a fool can learn from a wise answer.  ",
                "Bruce Lee"),
        new Quote("The attempt to escape from pain, is what creates more pain.",
                "Gabor Mate"),
        new Quote("In the end, it's not the years in your life that count. It's the life in your years.",
                "Abraham Lincoln"),
        new Quote("The greatest test of courage on earth is to bear defeat without losing heart.",
                "Robert Greene"),
        new Quote("To know your Enemy, you must become your Enemy.",
                "Sun Tzu"),
        new Quote(
                "Failure means you've now learned another valuable lesson that pushes you one step closer to success.",
                "Steve Harvey"),
        new Quote(
                "The first thing you learn in life is you're a fool. The last thing you learn in life is "
                        + "you're the same fool.  ",
                "Ray Bradbury"),
        new Quote("Before enlightenment; chop wood, carry water. After enlightenment; chop wood, carry water.",
                "Buddha"),
        new Quote("The biggest room in the world is the room for improvement.",
                "Unknown"),
        new Quote("Be approximately right rather than exactly wrong.",
                "John Tukey"),
        new Quote("Peace begins with a smile.",
                "Mother Teresa"),
        new Quote("Let each man exercise the art he knows.",
                "Aristophanes"),
        new Quote("None are more hopelessly enslaved than those who falsely believe they are free.",
                "Johann Wolfgang von Goethe"),
        new Quote(
                "By going within. Nowhere you can go is more peaceful - more free of interruptions - than "
                        + "your own soul.",
                "Marcus Aurelius"),
        new Quote(
                "Be the reason someone smiles. Be the reason someone feels loved and believes in the goodness "
                        + "in people.",
                "Roy T. Bennett"),
        new Quote(
                "It is in the heart that makes a man rich. He is rich according to what he is, not according to "
                        + "what he has.",
                "Henry Ward Beecher"),
        new Quote(
                "Ancient Rule of Twenty-one: if you do anything for twenty-one days in a row, it will be installed "
                        + "as a habit.",
                "Robin Sharma"),
        new Quote("To do great work one must be very idle as well as very industrious.",
                "Samuel Butler"),
        new Quote("There is no one giant step that does it. It's a lot of little steps.",
                "Peter A. Cohen"),
        new Quote(
                "You already have every characteristic necessary for success if you recognize, claim, develop and "
                        + "use them.",
                "Zig Ziglar"),
        new Quote(
                "It is under the greatest adversity that there exists the greatest potential for doing good, both "
                        + "for oneself and others.",
                "Dalai Lama"),
        new Quote("No duty is more urgent than that of returning thanks.",
                "James Allen"),
        new Quote("It doesn't matter how much you want. What really matters is how much you want it.",
                "Ralph Marston"),
        new Quote("Wisdom consists not so much in knowing what to do in the ultimate as knowing what to do next.",
                "Herbert Hoover"),
        new Quote("Make each day your masterpiece.",
                "John Wooden"),
        new Quote(
                "When you have vision it affects your attitude. Your attitude is optimistic rather than pessimistic. ",
                "Charles Swindoll"),
        new Quote("Always remember that you are absolutely unique. Just like everyone else. ",
                "Margaret Mead"),
        new Quote("It is during our darkest moments that we must focus to see the light.",
                "Aristotle"),
        new Quote("We know nothing of tomorrow, our business is to be good and happy today.",
                "Sydney Smith"),
        new Quote("Adults are just children who earn money.",
                "Kenneth Branagh"),
        new Quote("The sun shines upon good and bad alike.",
                "Hans Christian Andersen"),
        new Quote("Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. ",
                "Lao Tzu"),
        new Quote("Within every desire is the mechanics of its fulfillment.",
                "Deepak Chopra"),
        new Quote("Life is the dancer and you are the dance.",
                "Eckhart Tolle"),
        new Quote("Life comes at us in waves. We can't predict or control those waves, but we can learn to surf.",
                "Dan Millman"),
        new Quote(
                "Associate yourself with men of good quality, if you esteem your own reputation; for 'tis better "
                        + "to be alone than in bad company. ",
                "George Washington"),
        new Quote("The future is not a gift. It is an achievement.",
                "Robert F. Kennedy"),
        new Quote("The first rule of business; treat others like they want to treat you.",
                "Charles Dickens"),
        new Quote("Character is destiny.",
                "Heraclitus"),
        new Quote(
                "Yesterday is history, tomorrow is a mystery, today is God's gift, that's why we call it the present.",
                "Joan Rivers"),
        new Quote("The goal of an artist is to create the definitive work that cannot be surpassed.",
                "George Bernard Shaw"),
        new Quote("The person who cannot control his words shows that he cannot control himself.",
                "Robert Greene"),
        new Quote("Most people spend more time and energy going around problems than in trying to solve them. ",
                "Henry Ford"),
        new Quote("Do the difficult things while they are easy and do the great things while they are small.",
                "Lao Tzu"),
        new Quote("Life is a journey, not a destination.",
                "Dan Millman"),
        new Quote("The number one cause of failure is the fear of failure.",
                "Steve Harvey"),
        new Quote("Surrender to what is. Let go of what was. Have faith in what will be.",
                "Sonia Ricotti"),
        new Quote("People think about what they don't want and attract more of the same.",
                "Unknown"),
        new Quote("Whatever your mind can conceive and believe, it can achieve.",
                "Napoleon Hill"),
        new Quote(
                "Living a life that has a greater purpose and living up to it is the ultimate degree that we should "
                        + "strive for.",
                "Gurbaksh Chahal"),
        new Quote("Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
                "Helen Keller"),
        new Quote(
                "This is the real secret of life - to be completely engaged with what you are doing in the here and "
                        + "now. And instead of calling it work, realize it is play.",
                "Alan Watts"),
        new Quote("The whole world is a series of miracles, but we're so used to them we call them ordinary things.",
                "Hans Christian Andersen"),
        new Quote("Life is about not knowing and then doing something anyway.",
                "Mark Manson"),
        new Quote("You have to keep breaking your heart until it opens.",
                "Rumi"),
        new Quote("Our deeds determine us, as much as we determine our deeds.",
                "George Eliot"),
        new Quote("We suffer more often in imagination than in reality.  ",
                "Seneca"),
    };


    public static Quote getRandomQuote() {
        if (randomQuote == null) {
            int randomIndex = getRandomIndex();
            assert randomIndex > 0 && randomIndex < quotes.length : "Index out of range";
            randomQuote = quotes[randomIndex];
        }
        return randomQuote;
    }

    private static int getRandomIndex() {
        return ThreadLocalRandom.current().nextInt(0, quotes.length - 1);
    }
}
