@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ORDER_MODEL_COLOR_T4
skinparam classBackgroundColor ORDER_MODEL_COLOR
skinparam objectBackgroundColor ORDER_MODEL_COLOR
hide empty members

title "Initial TrackO Model State"

package {
    package Inventory {
        Object "__:InventoryList__" as InventoryList ITEM_MODEL_COLOR_T4 {
        }

        skinparam objectBackgroundColor ITEM_MODEL_COLOR
        Object "__:InventoryItem__" as Item1 {
            itemName = "Pen"
            quantity = 296
        }

        Object "__:InventoryItem__" as Item2 {
            itemName = "Eraser"
            quantity = 243
        }

        InventoryList --left> Item1
        InventoryList --> Item2
    }

    package Orders {
        Object "__:OrderList__" as OrderList ORDER_MODEL_COLOR_T4 {
        }
    }
}

@enduml
