@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TrackO *-right-> "1" InventoryList
TrackO *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- InventoryList
UniqueTagList -[hidden]down- InventoryList

UniqueTagList *-right-> "*" Tag
InventoryList -right-> Item

Item -up-> "*" Tag

Item *--> ItemName
Item *--> Description
Item *--> SellPrice
Item *--> CostPrice
Item *--> Quantity
@enduml
