@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ORDER_MODEL_COLOR_T4
skinparam classBackgroundColor ORDER_MODEL_COLOR

Class Order {
    - isPaid: boolean
    - isDelivered: boolean
    + isCompleted(): boolean
}
Class LocalDateTime
Class Name
Class ItemQuantityPair
Class "<<interface>>\nItem" as Item
Class RecordedItem implements Item
Class InventoryItem implements Item
Class Quantity
Class Address
Class Phone
Class Email

Order *--> "1" Name: by customer >
Order *--> "1" Phone: customer contactable at >
Order *--> "1" Email: customer contactable at >
Order *--right> "1" Address: to deliver to >
Order *--> "1" LocalDateTime: created at >
Order *---> "*" ItemQuantityPair : consists of >
ItemQuantityPair --> "1" Item
ItemQuantityPair --> "1" Quantity

note left of Order::"isCompleted()"
    This method returns true if and only if both isPaid and isDelivered are true
end note
@enduml
