@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ORDER_MODEL_COLOR_T4
skinparam classBackgroundColor ORDER_MODEL_COLOR
hide empty members

Class Order {
    - isPaid: boolean
    - isDelivered: boolean
    + isCompleted(): boolean
}
Class Name
Class Phone
Class Email
Class Address
Class ItemQuantityPair
Class LocalDateTime
Class Item
Class Quantity

Order *--> "1" Name: by >
Order *--> "1" Phone: contacted at >
Order *--> "1" Email: contacted at >
Order *--> "1" Address: to deliver to >
Order *--> "1" LocalDateTime: created at >
Order *---> "*" ItemQuantityPair : consists of >
ItemQuantityPair --> "1" Item
ItemQuantityPair --> "1" Quantity

note right of Order::"isCompleted()"
    This method returns true if and only if both isPaid and isDelivered are true
end note
@enduml
