@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


package Module {
    Class Module
}

package Schedule {
    show member
    Class Schedule {
        moduleCode
        classGroup
        startTime
        endTime
    }
    Class Venue {
        name
    }
    Enum "<<enum>>\nWeekdays" as Weekdays {
        Monday
        Tuesday
        Wednesday
        Thursday
        Friday
        Saturday
        Sunday
    }
    Enum "<<enum>>\nClassType" as ClassType {
        lec
        tut
        lab
        rec
    }
}

Schedule *--> "1" Venue
Schedule *--> "1" ClassType
Schedule *--> "1" Weekdays

Module -> "*" Schedule


@enduml

