@startuml
box Ui #F97181
participant ":MainWindow" as MainWindow #9D0012
end box

box Logic #C8C8FA
participant ":LogicManager" as LogicManager #3333C4
participant ":AddressBookParser" as AddressBookParser #3333C4
participant ":ClientCommandParser" as ClientCommandParser #3333C4
participant ":DeleteClientCommand" as DeleteClientCommand #3333C4
end box

[-> MainWindow : executeCommand\n(client -d 1)
activate MainWindow

MainWindow --> LogicManager : execute\n(client -d 1)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand\n(client -d 1)
activate AddressBookParser

create ClientCommandParser
AddressBookParser -> ClientCommandParser
activate ClientCommandParser
ClientCommandParser --> AddressBookParser
deactivate ClientCommandParser
AddressBookParser -> ClientCommandParser : parse\n(client -d 1)
activate ClientCommandParser

create DeleteClientCommand
ClientCommandParser -> DeleteClientCommand
activate DeleteClientCommand

DeleteClientCommand --> ClientCommandParser
deactivate DeleteClientCommand

ClientCommandParser --> AddressBookParser
deactivate ClientCommandParser

AddressBookParser --> LogicManager
deactivate AddressBookParser

LogicManager -> DeleteClientCommand : execute\n(model, ui)
activate DeleteClientCommand

DeleteClientCommand --> LogicManager : result
deactivate DeleteClientCommand

DeleteClientCommand -[hidden]-> LogicManager : result
destroy DeleteClientCommand

MainWindow <-- LogicManager : result
deactivate LogicManager
MainWindow --> MainWindow : swapClientListDisplay()

[<-- MainWindow : result
deactivate MainWindow

@enduml